### DISCUSSION TITLE
Mounting CephFS inside pod

### DISCUSSION THREAD

**Discussion by BonzTM** [ceph/ceph-csi#4109] [General]
I feel like an idiot starting this discussion, but I can't seem to find any answers.

Today, I'm using CephFS in-tree volume mounting to mount my CephFS inside my pods.  This allows me to have several pods (along with VMs) that can interact with the filesystem as it is.  Think of it like mounting an NFS share inside of a pod.

The in-tree plugin is deprecated with K8s 1.28.  The documentation now points to this CSI driver instead.  Everything I read about the CephFS implementation here is that it creates PVs on top of CephFS filesystems.  I want to mount the filesystem, not create a PV on top of it.  Am I understanding this wrong?  

What is the appropriate way to mount the existing filesystem with the in-tree plugin deprecated?  Mount it on each host and leverage hostpath?

**Comment by Rakshith-R** [comment]
@BonzTM you can make use of static provisioning https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md#cephfs-static-pvc .

**Reply by BonzTM** [reply]
> @BonzTM you can make use of static provisioning https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md#cephfs-static-pvc .

Thanks!

I don't currently have any subvolumes.  I would hope/assume it works off the root of an existing FS just as well?

Edit:  I created a static PV and used a directory off of my root volume instead of any subvolumes, and I got the result I expected!  Thanks a ton.  I feel like this information wasn't easily discoverable based on my needs, or I didn't have the correct search terminology.  I couldn't find it, so I hope this discussion helps the next person.

**Reply by bumarcell** [reply]
@BonzTM could you please tell me how you got it to work? 🙏 
I'm creating a static pv and a pvc on top as mentioned in the linked article, but I keep getting `timed out waiting for external-attacher of cephfs.csi.ceph.com` when I try to mount on a pod

**Reply by Madhu-1** [reply]
can you please check the logs of the external attacher in the cephfs provisioner pod (there will be 2 pods with leader election) which is responsible for it,  feel free to share pv object to reference

**Reply by bumarcell** [reply]
I checked both `csi-provisioner` and `csi-attacher` containers on the `csi-cephfsplugin-provisioner` pods and they don't seem to log anything.

For reference here's my pv definition:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-static-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Pi
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: r-ceph
    volumeAttributes:
      "clusterID": "7a1b9c1e-64ff-476c-8081-18b9773f6cd3"
      "fsName": "my-cephfs"
      "staticVolume": "true"
      "rootPath": /
    volumeHandle: cephfs-static-pv
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cephfs-static-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
  volumeName: cephfs-static-pv
  storageClassName: ""
  volumeMode: Filesystem
```

**Reply by Madhu-1** [reply]
I assume that this PV should have a bind to the PVC, but i don't see that binding in this yaml, i hope the PVC is in bound state and see increasing the loglevel in the csi-attacher sidecar, see if there are similar instances like this https://github.com/ceph/ceph-csi/issues/3476

**Reply by BonzTM** [reply]
> I checked both `csi-provisioner` and `csi-attacher` containers on the `csi-cephfsplugin-provisioner` pods and they don't seem to log anything.
> 
> For reference here's my pv definition:
> 
> ```
> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: cephfs-static-pv
> spec:
>   accessModes:
>   - ReadWriteMany
>   capacity:
>     storage: 1Pi
>   csi:
>     driver: cephfs.csi.ceph.com
>     nodeStageSecretRef:
>       name: rook-csi-cephfs-node
>       namespace: r-ceph
>     volumeAttributes:
>       clusterID: "7a1b9c1e-64ff-476c-8081-18b9773f6cd3"
>       fsName: "my-cephfs"
>       pool: data-ec0
>       staticVolume: "true"
>       rootPath: /
>     volumeHandle: cephfs-static-pv
>   persistentVolumeReclaimPolicy: Retain
>   volumeMode: Filesystem
> ```

The only 2 differences between your definition and mine, are the `volumeAttributes` field.
1. All my keys are quoted.  You'll notice that they are in the [docs](https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md#create-cephfs-static-pv) as well (with the exception of the rootPath value)
2. I do not have a pool defined.  Because it's CephFS, the pool is defined at the FS itself.

```yaml
    volumeAttributes:
      "clusterID": "7a1b9c1e-64ff-476c-8081-18b9773f6cd3"
      "fsName": "my-cephfs"
      "staticVolume": "true"
      "rootPath": /
```
