### DISCUSSION TITLE
Unable to create PV in k8s cluster, from image cloned via ceph UI

### DISCUSSION THREAD

**Discussion by Roniee007** [ceph/ceph-csi#5212] [Q&A]
i have tried many ways found online, one such is
- to create pv
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloned-pv
spec:
  capacity:
    storage: 3Gi  # Match the original size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    controllerExpandSecretRef:
      name: csi-rbd-secret
      namespace: default
    driver: rbd.csi.ceph.com
    volumeHandle: <clusterId>/<poolname>/<cloneimage>
    fsType: ext4
    nodeStageSecretRef:
      name: csi-rbd-secret
      namespace: default
    volumeAttributes:
      clusterID: "a8-8ab-0200"
      pool: "devk8spv"
      imageFeatures: layering
      imageName: test-clone
      parentImage: "devk8spv/ns-877/csi-vol-75a157cf1-11ef-a959-2e37e921463b@snap-5"
      radosNamespace: ns-877
      journalPool: devk8spv
      storage.kubernetes.io/csiProvisionerIdentity: 1740551340979-8081-rbd.csi.ceph.com
  mountOptions:
  - discard
  storageClassName: csi-rbd-sc
```
- pcv_clone
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-clone
  namespace: pv-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Match the PV size
  storageClassName: csi-rbd-sc
  volumeName: cloned-pv
```
these scripts are running successfully, but when i mount it to a pod an error occurs regarding "unable to decode volume ID"

Can anyone guide me with the proper way to create a pv from cloned image on ceph UI.
