### ISSUE TITLE
CephFS Volume has Permission Denied error

### ISSUE THREAD

**Issue by akgunjal** [ceph/ceph-csi#1097]
# Describe the bug #
CephFS Volume throws Permission Denied error when accessing the volume from pod.

I created a CephFS based PVC on the OpenShift cluster OCP 4.3 version. When I create a pod and mount it in the pod I get `Permission Denied` error while trying to access the mount path. It works fine when I create a privileged container. What is the way to use the CephFS volume using non-privileged container.

# Environment details #
Openshift OCP 4.3
OCS 4.3

- Image/version of Ceph CSI driver :
- Helm chart version :
- Kernel version :
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version :
- Ceph cluster version :

# Steps to reproduce #

Create a PVC with CephFS.
Create a pod using CephFS PVC
Exec into the pod and move to mount path
Run `ls` command

# Actual results #
`ls: cannot open directory '.': Permission denied`

# Expected behavior #
It should work fine with non privileged container to access volume.

**Comment by Madhu-1** [comment]
Please provide the pod template you used to your testing

**Comment by Madhu-1** [comment]
This is already covered in e2e testing https://github.com/ceph/ceph-csi/blob/c2d4200bd87976f5a65b15f58b3609624a48195d/e2e/utils.go#L808 

Also provide the ceph user capabilities used for mounting pvc

**Comment by akgunjal** [comment]
@Madhu-1 : I have used `ReadWriteMany` for PVC. Posting the PVC and pod yamls for your reference.

**PVC:**
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc2 # user can choose any name as per kubernetes
  annotations:
    volume.beta.kubernetes.io/storage-class: "ocs-storagecluster-cephfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
```

**Pod:**
```
apiVersion: v1
kind: Pod
metadata:
  name: logpod2
spec:
  containers:
  - image: mongo #image name which should be avilable within cluster
#    securityContext:
#      privileged: true
    name: container-name # name of the container inside POD
    volumeMounts:
    - mountPath: /myvolumepath  # mount path for pvc from container
      name: pvc-name # pvc name for this pod
  volumes:
  - name: pvc-name  # volume resource name in this POD, user can choose any name as per kubernetes 
    persistentVolumeClaim:
      claimName: pvc2
```

In the above file, I have commented `securityContext` to reproduce the issue. If I uncomment that it will work.

**Comment by Madhu-1** [comment]
I don't think this is something with CSI, because the above-pasted pod yaml is same as https://github.com/ceph/ceph-csi/blob/master/examples/cephfs/pod.yaml what we use in our testing, and even we are giving full permission for the target path https://github.com/ceph/ceph-csi/blob/master/internal/cephfs/nodeserver.go#L212

**Comment by akgunjal** [comment]
@Madhu-1 : The issue I get is when I use CephFS storage class. So I was directed to open a issue here. Is this the right place for CephFS issues? I an easily reproduce the issue with my yaml files.

**Comment by jarrpa** [comment]
@Madhu-1 Can you or someone else help him troubleshoot what might be going wrong? Can he provide any logs, like say for the cephfs provisioner or node plugin?

**Comment by Madhu-1** [comment]
Csi-cephfsplugin container logs from the cephfs-plugin pod from the node on which the app is mounted might be helpful. @akgunjal can you please provide the same.

**Comment by akgunjal** [comment]
[cephfsplugin.log.zip](https://github.com/ceph/ceph-csi/files/4700816/cephfsplugin.log.zip)
@Madhu-1 : Please find the the cephfs plugin logs where the pod is mounted.

**Comment by Madhu-1** [comment]
@akgunjal I don't see any error in the log. can you check the mountpoint permission on the app pod?

**Comment by akgunjal** [comment]
This is a issue when we use non-root user. In my case mongodb is a non root user. Is there some way we can set uid/gid for volumes in cephfs. I guess that should resolve this.

Please check the permissions on mount path.
```
root@logpod1:/# ls -l
drwxrwxrwx    1 root root      0 May 29 08:18 myvolumepath
root@logpod1:/# ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
mongodb       1  0.4  0.1 1583008 94788 ?       Ssl  08:20   0:18 mongod --bind_ip_all
root         67  0.0  0.0  18496  2112 pts/0    Ss   09:35   0:00 bash
root         79  0.0  0.0  34392  1540 pts/0    R+   09:35   0:00 ps aux
root@logpod1:/# 
```

**Comment by Madhu-1** [comment]
Am able to write data with normal user. @humblec Am i missing something? 

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: csicephfs-demo-pod
spec:
  # Allow non-root user to access PersistentVolume
  securityContext:
    fsGroup: 1000
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - name: mypvc
         mountPath: /var/lib/www/html
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: cephfs-pvc
       readOnly: false
```
```bash
[🎩︎]mrajanna@localhost rook $])`exec': kubectl exec -it csicephfs-demo-pod sh
# df -h
Filesystem                                                                     Size  Used Avail Use% Mounted on
overlay                                                                         17G  4.0G   12G  27% /
tmpfs                                                                           64M     0   64M   0% /dev
tmpfs                                                                          1.4G     0  1.4G   0% /sys/fs/cgroup
/dev/vda1                                                                       17G  4.0G   12G  27% /etc/hosts
shm                                                                             64M     0   64M   0% /dev/shm
10.108.115.205:6789:/volumes/csi/csi-vol-e12cdfdb-a18d-11ea-b198-0242ac110008  1.0G     0  1.0G   0% /var/lib/www/html
tmpfs                                                                          1.4G   12K  1.4G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                          1.4G     0  1.4G   0% /proc/acpi
tmpfs                                                                          1.4G     0  1.4G   0% /proc/scsi
tmpfs                                                                          1.4G     0  1.4G   0% /sys/firmware
# cd /var/lib/www
# ls -l
total 0
drwxrwsrwx 2 root 1000 1 May 29 09:43 html
# echo safdsa >htlm/a
# cat htlm/a
safdsa
```

**Comment by Madhu-1** [comment]
Am able to write data with normal user. @humblec Am i missing something?
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: csicephfs-demo-pod
spec:
  # Allow non-root user to access PersistentVolume
  securityContext:
    fsGroup: 1000
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - name: mypvc
         mountPath: /var/lib/www/html
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: cephfs-pvc
       readOnly: false
```
```bash
[🎩︎]mrajanna@localhost rook $])`exec': kubectl exec -it csicephfs-demo-pod sh
# df -h
Filesystem                                                                     Size  Used Avail Use% Mounted on
overlay                                                                         17G  4.0G   12G  27% /
tmpfs                                                                           64M     0   64M   0% /dev
tmpfs                                                                          1.4G     0  1.4G   0% /sys/fs/cgroup
/dev/vda1                                                                       17G  4.0G   12G  27% /etc/hosts
shm                                                                             64M     0   64M   0% /dev/shm
10.108.115.205:6789:/volumes/csi/csi-vol-e12cdfdb-a18d-11ea-b198-0242ac110008  1.0G     0  1.0G   0% /var/lib/www/html
tmpfs                                                                          1.4G   12K  1.4G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                          1.4G     0  1.4G   0% /proc/acpi
tmpfs                                                                          1.4G     0  1.4G   0% /proc/scsi
tmpfs                                                                          1.4G     0  1.4G   0% /sys/firmware
# cd /var/lib/www
# ls -l
total 0
drwxrwsrwx 2 root 1000 1 May 29 09:43 html
# echo safdsa >html/a
# cat html/a
safdsa
```
