### ISSUE TITLE
RBAC rules for configmaps

### ISSUE THREAD

**Issue by pohly** [ceph/ceph-csi#115]
When https://github.com/ceph/ceph-csi/pull/113 was merged, the https://github.com/ceph/ceph-csi/blob/master/deploy/rbd/kubernetes/csi-nodeplugin-rbac.yaml file wasn't updated.

I've not tried it with exactly that file, but in a custom deployment the result was that RBAC prevented updating the config map.

I had to add something like this:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: rbd-configmap-updater
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch", "list", "get", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: rbd-node-rb
subjects:
  - kind: ServiceAccount
    name: rbd-cluster-sa
    namespace: default
roleRef:
  kind: Role
  namespace: default
  name: rbd-configmap-updater
  apiGroup: rbac.authorization.k8s.io
```

I suspect that the set of verbs could be smaller, but haven't checked.
