### ISSUE TITLE
csi-snapshotter not working error the snapshot source is not the right type

### ISSUE THREAD

**Issue by DavidePrette** [ceph/ceph-csi#1223]
Hi everyone,
I configured Ceph-csi-rbd with helm (chart version v2.1.2) correctly, everything work as excepted but the snapshot no.
This is my error:
```
kubectl describe volumesnapshot rbd-pvc-snapshot 
Name:         rbd-pvc-snapshot
Namespace:    default
Labels:       <none>
Annotations:  API Version:  snapshot.storage.k8s.io/v1alpha1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2020-07-09T14:21:47Z
  Generation:          1
  Managed Fields:
    API Version:  snapshot.storage.k8s.io/v1alpha1
    Manager:         csi-snapshotter
    Operation:       Update
    Time:            2020-07-09T14:21:47Z
  Resource Version:  2703884
  Self Link:         /apis/snapshot.storage.k8s.io/v1alpha1/namespaces/default/volumesnapshots/rbd-pvc-snapshot
  UID:               b66cdd0b-9785-4edc-bf18-b1a0a606f05b
Spec:
  Source:
    Persistent Volume Claim Name:  rbd-pvc
  Volume Snapshot Class Name:      csi-rbdplugin-snapclass
Status:
  Creation Time:  <nil>
  Error:
    Message:     Failed to set default snapshot class with error the snapshot source is not the right type. Expected PersistentVolumeClaim, Got 
    Time:        2020-07-09T14:21:47Z
  Ready To Use:  false
  Restore Size:  <nil>
Events:
  Type     Reason                         Age   From                              Message
  ----     ------                         ----  ----                              -------
  Warning  SetDefaultSnapshotClassFailed  12m   csi-snapshotter rbd.csi.ceph.com  Failed to set default snapshot class with error the snapshot source is not the right type. Expected PersistentVolumeClaim, Got
```
Definition of snapshot:
```
---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: rbd-pvc-snapshot
spec:
  volumeSnapshotClassName: csi-rbdplugin-snapclass
  source:
    persistentVolumeClaimName: rbd-pvc

```

This is the snapshotclass config:
```
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: csi-rbdplugin-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: rbd.csi.ceph.com
parameters:
  clusterID: 3e0ed2a6-f055-4222-9999-32fd0528a1d3
  csi.storage.k8s.io/snapshotter-secret-name: csi-rbd-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: ceph-csi-rbd
deletionPolicy: Delete
```
OS: Ubuntu 20.04
K8: version 18.3 from rancher
Ceph nautilus version 14.2.10
