### ISSUE TITLE
RBD: Enable support for reflink on XFS

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1256]
# Describe the feature you'd like to have #

XFS supports reflinking that makes it possible to do copy-on-write with the `copy_file_range()` syscall. Not all Linux kernels support this feature, and when enabled on an RBD image, kernels without support will not be able to mount the filesystem.

Being conservative, and preventing breakage of users that migrate from Ceph Nautilus to Ceph Octopus based container images, reflink for XFS has been disabled by default (#966).

Users may want to enable reflink support on Kubernetes clusters that have current Linux kernels. The following proposed option in a StorageClass would make this possible:

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-rbd-sc
provisioner: rbd.csi.ceph.com
parameters:
   pool: rbd
   reflink: disabled|enabled|auto
```
Values for the new `reflink` option:
- **disabled**: detect support in `mkfs.xfs`, and pass `-m reflink=0` if supported (default)
- **enabled**: force enabling, always pass `-m reflink=1`, will fail to mount on old Linux kernels
- **auto**: do nothing, do not pass `-m reflink=` and make this default in some next Ceph-CSI version

# Additional context #

See #966 for related problems.
