### ISSUE TITLE
RBD PVC with multi access mode (RWO and ROX) can not be mounted readwrite

### ISSUE THREAD

**Issue by houz42** [ceph/ceph-csi#1406]
# Describe the bug #

Mounting a new RBD PVC with 2 access modes (RWO and ROX) to a pod by readOnly=false will be failed. The pod stucks on "containerCreating" and the error message is "cannot mount unformatted disk /dev/rbd1 as we are manipulating it in read-only mode". 

If mounting a used RBD PVC, the pod starts, but the PVC is mounted read only, no matter readOnly is set or not.

# Environment details #

- Image/version of Ceph CSI driver : v3.1.0
- Helm chart version :
- Kernel version : 5.2.21-050221-generic
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : krbd
- Kubernetes cluster version : v1.17.0
- Ceph cluster version : 14.2.4

# Steps to reproduce #

1. Create PVC:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rbd
spec:
  accessModes:
  - ReadOnlyMany
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-rbd
  volumeMode: Filesystem
```

2. Create pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: use-pvc-rbd
spec:
  containers:
    - name: main
      image: busybox
      volumeMounts:
      - name: rbd
        mountPath: /data
  volumes:
  - name: rbd
    persistentVolumeClaim:
      claimName: pvc-rbd
```

1. Wait until the pod is scheduled and stuck on "containerCreating", describe the pod to see the error message:
```
Events:
  Type     Reason                  Age              From                     Message
  ----     ------                  ----             ----                     -------
  Normal   Scheduled               10s              default-scheduler        Successfully assigned ***/use-pvc-rbd to ***19
  Normal   SuccessfulAttachVolume  10s              attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-221648a7-6fd6-453f-90d9-229c508001a1"
  Warning  FailedMount             4s (x4 over 9s)  kubelet, ***19          MountVolume.MountDevice failed for volume "pvc-221648a7-6fd6-453f-90d9-229c508001a1" : rpc error: code = Internal desc = cannot mount unformatted disk /dev/rbd1
as we are manipulating it in read-only mode
```

# Actual results #

Pod cannot start

# Expected behavior #

Pod starts and writes to the pvc mount path with no error

# Logs #

I have downgraded the rbd provisioner and node plugins to v2.1.x with a custom patch, and can not find the logs.

# Additional context #

1. feature request for "ROX RBD support": #725
2. an e2e test for "ROX RBD support" (closed) : #947 
3. the implementation of "ROX RBD support" in v3.x: #949 

e2e test in #949 is not exactly the same in #947, and I believe this is the reason.

in #947, a user should:
1. create a PVC with 2 access modes: RWO and ROX
2. create a pod, mount the pvc with write access, write data to the PVC
3. stop the first pod
4. create more than 1 pods, all of which mount the PVC with readOnly=true
5. all the pods can start and read the PVC

but in #949, user should:
1. create a PVC with 1 access mode: RWO
2. create a pod, mount the pvc with write access, write data to the PVC
3. stop the first pod
4. create a snapshot for the PVC
5. create more than 1 pods, all of which mount the snapshot with readOnly=true
5. all the pods can start and read the snapshot

**Comment by Madhu-1** [comment]
am PVC cannot be used with both access mode at a given point of time.

**Comment by houz42** [comment]
> am PVC cannot be used with both access mode at a given point of time.

It is not "at a given point of time."

the first pod is stopped when the other "reader pods" starts

**Comment by Madhu-1** [comment]
please provide the logs of all node plugins. need to check `accessmode`  sent in the NodeStageRequest

**Comment by houz42** [comment]
@Madhu-1  Sorry, I'm afraid it is not possible. I downgraded the node plugins to v2.1.x. I will try the elk later.

And Thanks for your reponse and great work.

**Comment by Madhu-1** [comment]
@houz42 please provide the exact steps to reproduce this one, so that we can also try it out locally

**Comment by Madhu-1** [comment]
>Mounting a new RBD PVC with 2 access modes (RWO and ROX) to a pod by readOnly=false will be failed. The pod stucks on "containerCreating" and the error message is "cannot mount unformatted disk /dev/rbd1 as we are manipulating it in read-only mode".

This can happen only if the filesystem format is not present on the rbd device and when you tried to mount the PVC as readonly. but i would like to see the corner cases if we are missing any. getting the nodeplugin logs helps a lot to see whats happening

**Comment by nixpanic** [comment]
> @houz42 please provide the exact steps to reproduce this one, so that we can also try it out locally

Testing this quickly on an OpenShift cluster that I have available, shows it is possible to reproduce the issue with a few steps.

1. create a PVC woth RWO and ROX modes:
```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: busybox-srv
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
```
2. create a pod that writes something to the PVC
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-writer
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    args:
    - sh
    - -c
    - "echo Hello World > /srv/README.txt"
    volumeMounts:
      - name: srv
        mountPath: /srv
        readOnly: false
  volumes:
  - name: srv
    persistentVolumeClaim:
      claimName: busybox-srv
```
3. wait until the previous pod is in `completed` state
4. create a pod that reads the created file:
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-reader-1
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    args:
    - sh
    - -c
    - "cat /srv/README.txt ; sleep 1h"
    volumeMounts:
      - name: srv
        mountPath: /srv
        readOnly: true
  volumes:
  - name: srv
    persistentVolumeClaim:
      claimName: busybox-srv
```
4. check with `kubectl logs busybox-reader-1` that the file is available
5. create a 2nd pod that reads the file, while the previous pod is running (`sleep 1h`)
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-reader-2
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    args:
    - sh
    - -c
    - "cat /srv/README.txt ; sleep 1h"
    volumeMounts:
      - name: srv
        mountPath: /srv
        readOnly: true
  volumes:
  - name: srv
    persistentVolumeClaim:
      claimName: busybox-srv
```

The `busybox-reader-2` pod does not become `running`, it stays in `containercreating`:
```
NAME               READY     STATUS              RESTARTS   AGE
busybox-reader-1   1/1       Running             0          7m17s
busybox-reader-2   0/1       ContainerCreating   0          6m25s
busybox-writer     0/1       Completed           0          9m59s
```
The events when describing the 2nd pod contain the following:
```
Events:
  Type     Reason                  Age               From                                  Message
  ----     ------                  ----              ----                                  -------
  Normal   Scheduled               <unknown>         default-scheduler                     Successfully assigned issue-1406/busybox-reader-2 to ip-10-0-165-76.ec2.internal
  Normal   SuccessfulAttachVolume  7m                attachdetach-controller               AttachVolume.Attach succeeded for volume "pvc-cdc1cc98-adb1-4803-bfdb-9cff20ee2be3"
  Warning  FailedMount             5m                kubelet, ip-10-0-165-76.ec2.internal  Unable to attach or mount volumes: unmounted volumes=[srv], unattached volumes=[default-token-42pds srv]: timed out waiting for the condition
  Warning  FailedMount             47s (x7 over 6m)  kubelet, ip-10-0-165-76.ec2.internal  MountVolume.MountDevice failed for volume "pvc-cdc1cc98-adb1-4803-bfdb-9cff20ee2be3" : rpc error: code = Internal desc = rbd image ocs-storagecluster-cephblockpool/csi-vol-273c63ad-e2ba-11ea-b950-0a580a800209 is still being used
  Warning  FailedMount             43s (x2 over 3m)  kubelet, ip-10-0-165-76.ec2.internal  Unable to attach or mount volumes: unmounted volumes=[srv], unattached volumes=[srv default-token-42pds]: timed out waiting for the condition
```

The key is that the rbd-nodeplugin detects that there is a watcher on the RBD image (from events):
```
rbd image ocs-storagecluster-cephblockpool/csi-vol-273c63ad-e2ba-11ea-b950-0a580a800209 is still being used
```

If it is possible for the nodeplugin to know that the volume is to be used as ROX, there is no check for watchers needed. It should be sufficient to trust the (kubernetes) scheduler to not start a pods with conflicting accessModes at the same time.
