### ISSUE TITLE
Inline Volume Support for K8s Pod

### ISSUE THREAD

**Issue by dpaks** [ceph/ceph-csi#1461]
# Describe the bug #

I'm trying to unsuccessfully create a k8s pod with inline CSI filesystem static volume. The static volume mount works if I create a persistent volume.

# Environment details #

- Image/version of Ceph CSI driver : ceph/ceph:v15.2.4
- Helm chart version : rook's v1.4.2
- Kernel version : 5.0.0-1029-gcp
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : No PVC involved
- Kubernetes cluster version : 1.15.3
- Ceph cluster version : v15.2.4

# Steps to reproduce #

Apply foll. yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: inline-csicephfs-pod
  namespace: xx-infra
spec:
  containers:
  - name: eman
    image: ubuntu:20.04
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: vol
      mountPath: /mnt
  volumes:
  - name: vol
    csi:
      driver: xx-infra.cephfs.csi.ceph.com
      nodePublishSecretRef:
        name: csi-cephfs-secret
      volumeAttributes:
        "clusterID": "xx-infra"
        "fsName": "myfs"
        "staticVolume": "true"
        "rootPath": "/"
```

# Actual results #

The Pod "inline-csicephfs-pod" is invalid: 
* spec.volumes[0]: Required value: must specify a volume type
* spec.containers[0].volumeMounts[0].name: Not found: "vol"

# Expected behavior #

Successful pod creation

# Additional context #

If I create the foll. PV, I can mount it in the pod.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myPV
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  csi:
    driver: xx-infra.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: csi-cephfs-secret
      namespace: xx-infra
    volumeAttributes:
      "clusterID": "xxx-infra"
      "fsName": "myfs"
      "staticVolume": "true"
      "rootPath": "/"
    volumeHandle: rand
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```
