### ISSUE TITLE
Encryption for RBD volumes failed when encrypted was enabled

### ISSUE THREAD

**Issue by olivejing** [ceph/ceph-csi#1511]
# Describe the bug #

I am trying the encrytion for RBD volumes, guide from cephcsi:
https://github.com/ceph/ceph-csi/blob/master/docs/deploy-rbd.md
```
To enable encryption set encrypted option in storage class to "true" and set encryption passphrase in kubernetes secrets under encryptionPassphrase key.

To use different passphrase you need to have different storage classes and point to a different K8s secrets (different csi.storage.k8s.io/node-stage-secret-name and csi.storage.k8s.io/node-stage-secret-namespace).
```

PVC stucks at Pending status:
```
# kubectl describe pvc cinfo-cephrbd-data-cinfo-cephrbd-0
Name:          cinfo-cephrbd-data-cinfo-cephrbd-0
Namespace:     default
StorageClass:  csi-cephrbd-test1
Status:        Pending
Volume:
Labels:        app=cinfo-cephrbd
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    cinfo-cephrbd-0
Events:
  Type     Reason                Age                   From                                                                     Message
  ----     ------                ----                  ----                                                                     -------
  Warning  ProvisioningFailed    59s (x6 over 2m14s)   persistentvolume-controller                                              storageclass.storage.k8s.io "csi-cephrbd-test1" not found
  Normal   ExternalProvisioning  14s (x13 over 4m25s)  persistentvolume-controller                                              waiting for a volume to be created, either by external provisioner "rbd.csi.ceph.com" or manually created by system administrator
  Normal   Provisioning          9s (x10 over 4m25s)   rbd.csi.ceph.com_olive-2006-c-s-01_5ad08db3-edf3-4b0b-ae10-b08617e4a204  External provisioner is provisioning volume for claim "default/cinfo-cephrbd-data-cinfo-cephrbd-0"
  Warning  ProvisioningFailed    9s (x10 over 4m25s)   rbd.csi.ceph.com_olive-2006-c-s-01_5ad08db3-edf3-4b0b-ae10-b08617e4a204  failed to provision volume with StorageClass "csi-cephrbd-test1": rpc error: code = InvalidArgument desc = invalid encryption kms configuration: missing encryption passphrase in secrets
```

new created secret and StorageClass:
```
# cat csi-cephrbd-secret-test1
apiVersion: v1
data:
  userID: YWRtaW4=
  userKey: QVFEbmE3NWNUQzJ2T2hBQWNFa0lGMGNpZm9TOVM0Mzh6VTBIM1E9PQ==
  encryptionPassphrase: dGVzdDEK
kind: Secret
metadata:
  name: csi-cephrbd-test1
  namespace: test1

# cat csi-cephrbd-sc-test1
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cephrbd-test1
mountOptions:
- discard
parameters:
  clusterID: 7671882a-3c85-44de-bbba-7ffffe3c573b
  csi.storage.k8s.io/controller-expand-secret-name: csi-cephrbd
  csi.storage.k8s.io/controller-expand-secret-namespace: ncms
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: csi-cephrbd-test1
  csi.storage.k8s.io/node-stage-secret-namespace: test1
  csi.storage.k8s.io/provisioner-secret-name: csi-cephrbd
  csi.storage.k8s.io/provisioner-secret-namespace: ncms
  imageFeatures: layering
  imageFormat: "2"
  mounter: kernel
  pool: volumes
  encrypted: "true"
provisioner: rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

From the error log, it checks KMS config although i don't use KMS.

# Environment details #

- cephcsi : v2.1.2
- Kernel version : # uname -a
Linux olive-2006-c-s-01 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes cluster version : v1.18.8

# Steps to reproduce #

1. prepare ceph cluster and cephcsi environment
2. create new secret with  encryptionPassphrase key
3. create new StorageClass with encrypted: "true", csi.storage.k8s.io/node-stage-secret-name uses the new created secret.
4, create pvc with the new StorageClass, and check pvc status

# Actual results #

PVC stucks at Pending status.

# Expected behavior #

Expect the encryption for RBD volume works
