### ISSUE TITLE
RBD striping image feature support

### ISSUE THREAD

**Issue by togoschi** [ceph/ceph-csi#1555]
# Describe the feature you'd like to have #

CSI RBD currently supports only the `layering` image feature. I think it will be a good idea to support the `striping v2` image feature too. If possible the parameter `imageFeatures` becomes another value e.g `striping`

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-rbd-sc
provisioner: rbd.csi.ceph.com
parameters:
   pool: rbd
   imageFeatures: striping
```

# What is the value to the end user? (why is it a priority?) #

I think I/O performance on RBD PV's could be possibly better with striping feature.

Description of `striping v2` image feature in Ceph RBD config reference documentation:
"Striping spreads data across multiple objects. Striping helps with parallelism for sequential read/write workloads"
