### ISSUE TITLE
RBD VolumeSnapshotClass not found

### ISSUE THREAD

**Issue by tuxassault** [ceph/ceph-csi#1556]
**Kubernetes Version: 1.18.2
Ceph CSI Version: 3.1.0**

I deployed the Ceph CSI provisioner to my Kubernetes cluster using the instructions for Helm 3.0 at https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/README.md

After doing so, and configuring the details in the configmap, I was able to successfully create RBD persistent volumes and claims. I have also configured my kube-apiserver to enable the feature gates **VolumeSnapshotDataSource=true**

```
$ ps aux | grep api
root       413 15.4 12.9 705172 501024 ?       Ssl  17:47   7:53 kube-apiserver --advertise-address=192.168.2.64 --allow-privileged=true --anonymous-auth=True --apiserver-count=3 --authorization-mode=Node,RBAC --bind-address=0.0.0.0 --client-ca-file=/etc/kubernetes/ssl/ca.crt --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=False --enable-bootstrap-token-auth=true --endpoint-reconciler-type=lease --etcd-cafile=/etc/ssl/etcd/ssl/ca.pem --etcd-certfile=/etc/ssl/etcd/ssl/node-flame-k8s-master-nf-1.pem --etcd-keyfile=/etc/ssl/etcd/ssl/node-flame-k8s-master-nf-1-key.pem --etcd-servers=https://192.168.2.64:2379,https://192.168.2.146:2379,https://192.168.2.212:2379 --feature-gates=CSIMigration=true,CSIMigrationOpenStack=true,ExpandCSIVolumes=true,VolumeSnapshotDataSource=true,BlockVolume=true,CSIBlockVolume=true --insecure-port=0 --kubelet-client-certificate=/etc/kubernetes/ssl/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/ssl/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP --profiling=False --proxy-client-cert-file=/etc/kubernetes/ssl/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/ssl/front-proxy-client.key --request-timeout=1m0s --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/ssl/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --runtime-config= --secure-port=6443 --service-account-key-file=/etc/kubernetes/ssl/sa.pub --service-cluster-ip-range=10.233.0.0/18 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/etc/kubernetes/ssl/apiserver.crt --tls-private-key-file=/etc/kubernetes/ssl/apiserver.key
```

However, this does not appear to be enough to get this going, as when i apply the following YAML

```
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: csi-rbdplugin-snapclass
driver: rbd.csi.ceph.com
parameters:
  # String representing a Ceph cluster to provision storage from.
  # Should be unique across all Ceph clusters in use for provisioning,
  # cannot be greater than 36 bytes in length, and should remain immutable for
  # the lifetime of the StorageClass in use.
  # Ensure to create an entry in the configmap named ceph-csi-config, based on
  # csi-config-map-sample.yaml, to accompany the string chosen to
  # represent the Ceph cluster in clusterID below
  clusterID: 73482144-ade1-4ea4-8171-4d16afa02ce8

  # Prefix to use for naming RBD snapshots.
  # If omitted, defaults to "csi-snap-".
  snapshotNamePrefix: "flame-snap-"

  csi.storage.k8s.io/snapshotter-secret-name: csi-rbd-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: default
deletionPolicy: Delete
```

Kubernetes errors with:

`error: unable to recognize "snapshotclass.yaml": no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1beta1"`

Can someone help me figure out what is wrong?
