### ISSUE TITLE
How to create pre-provisioned volume without using the plugin.

### ISSUE THREAD

**Issue by f1-outsourcing** [ceph/ceph-csi#1810]
Sorry for asking this undoubtedly simple question. I have looked a bit at the source and I just cannot discover where and how this volumeID is saved with the rbd image.

I would like to create the images via the normal ceph command line. I know the plugin returns the volumeID that I can use in my task definition. 

But how can I create an image with `rbd create` and then add this volumeID to my image after I created it.

```
[@~]# rbd info csi-vol-2d0aee22-4128-11eb-a878-0050563001a1 -p app
rbd image 'csi-vol-2d0aee22-4128-11eb-a878-0050563001a1':
     size 96 MiB in 24 objects
     order 22 (4 MiB objects)
     snapshot_count: 0
     id: 4d1eee6589631e
     block_name_prefix: rbd_data.4d1eee6589631e
     format: 2
     features: layering
     op_features:
     flags:
     create_timestamp: Fri Dec 18 12:57:17 2020
     access_timestamp: Fri Dec 18 12:57:17 2020
     modify_timestamp: Fri Dec 18 12:57:17 2020
```

```
[@~]# rbd image-meta ls csi-vol-2d0aee22-4128-11eb-a878-0050563001a1 -p app
There are 0 metadata on this image.
```
