### ISSUE TITLE
Support ceph cluster running without cephx

### ISSUE THREAD

**Issue by karibertils** [ceph/ceph-csi#1815]
# Describe the feature you'd like to have #

I want to use ceph-csi on cluster running without cephx due to performance reasons.

# What is the value to the end user? (why is it a priority?) #

Disabling cephx can be helpful to squeeze extra performance when doing massive small IO with ceph. Obviously there are security implications for the cluster, and it should only be done in specific scenarios.

# How will we know we have a good solution? (acceptance criteria) #

Standard features like creating, destroying, mounting, unmounting, etc work.

# Additional context #

Adding the following to ```ceph-csi-rbd-nodeplugin``` daemonset and ```ceph-csi-rbd-provisioner``` deployment seems to make everything work, so this should be simple to support.
```
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - |
                sleep 5 &&
                sed -i 's/cephx/none/' /etc/ceph/ceph.conf &
```
