### ISSUE TITLE
PVC stuck on pending state

### ISSUE THREAD

**Issue by lfdominguez** [ceph/ceph-csi#1817]
# Describe the bug #

I deployed the helm version of ceph-csi, all work ok, but when i need to create a PVC always stuck on pending state, the logs show
```failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-60d9b518-1d14-40f2-a1aa-e3af0b92e02e already exists```

# Environment details #

- Image/version of Ceph CSI driver : 3.2.0
- Helm chart version : stable
- Kernel version : 5.4.0-58-generic
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : krbd
- Kubernetes cluster version : v1.18.13+rke2r1
- Ceph cluster version : 15.2.5 (octopus)

# Steps to reproduce #

1. Setup details: `helm3 install --values ceph_values.yaml --namespace "ceph-csi-rbd" "ceph-csi-rbd" ceph-csi/ceph-csi-rbd`
2. Deployment to trigger the issue 
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-block-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
```
3. See error

# Actual results #

PVC in pending state

# Expected behavior #

PVC in bond state with the rbd image on ceph cluster created

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

Full provisioner log 
[csi-provisioner.log](https://github.com/ceph/ceph-csi/files/5739665/csi-provisioner.log)

Full csi-cephfsplugin log [csi-rbdplugin.log](https://github.com/ceph/ceph-csi/files/5739664/csi-rbdplugin.log)
