### ISSUE TITLE
Getting all the time rpc error: code = Internal desc = invalid feature

### ISSUE THREAD

**Issue by LNAhri** [ceph/ceph-csi#1937]
# Describe the bug #

Installed the Ceph-csi stuff completly new based on the Ceph Doku. The ceph Cluster is a fresh installed version based on the management from Proxmox-VE.

# Environment details #

- Image/version of Ceph CSI driver : canary
- Ceph cluster version : 15.2.9
- Kubernetes cluster version : 
Kernel version
5.4.0-70-generic
OS Image
Ubuntu 20.04.2 LTS
Container runtime version
containerd://1.3.7
kubelet version
v1.19.8-34+811e9feeade1d3
kube-proxy version
v1.19.8-34+811e9feeade1d3
Operating system
linux
Architecture
amd64

# Steps to reproduce #

Just install anything like stated here:
https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/#configure-ceph-csi

csi-main
ourceVersion:"27458", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/raw-block-pvc"
I0327 14:46:01.736851       1 controller.go:731] CreateVolumeRequest name:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" capacity_range:<required_bytes:1073741824 > volume_capabilities:<block:<> access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"clusterID" value:"065d7a87-b64f-4d80-9d60-46a1598ff07d" > parameters:<key:"csi.storage.k8s.io/pv/name" value:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" > parameters:<key:"csi.storage.k8s.io/pvc/name" value:"raw-block-pvc" > parameters:<key:"csi.storage.k8s.io/pvc/namespace" value:"kube-system" > parameters:<key:"pool" value:"kubernetes" > secrets:<key:"userID" value:"kubernetes" > secrets:<key:"userKey" value:"jjjjkj" > 
I0327 14:46:01.738099       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:01.738130       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0327 14:46:01.742915       1 connection.go:185] GRPC response: {}
I0327 14:46:01.743112       1 connection.go:186] GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:01.743176       1 controller.go:752] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:01.743380       1 controller.go:1099] Final error received, removing PVC 135cf774-db66-4d34-9d29-654d6527bb16 from claims in progress
W0327 14:46:01.743434       1 controller.go:958] Retrying syncing claim "135cf774-db66-4d34-9d29-654d6527bb16", failure 0
I0327 14:46:01.743544       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
E0327 14:46:01.743578       1 controller.go:981] error syncing claim "135cf774-db66-4d34-9d29-654d6527bb16": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:01.743681       1 controller.go:1332] provision "kube-system/raw-block-pvc" class "csi-rbd-sc": started
I0327 14:46:01.744167       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/raw-block-pvc"
I0327 14:46:01.753047       1 controller.go:731] CreateVolumeRequest name:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" capacity_range:<required_bytes:1073741824 > volume_capabilities:<block:<> access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"clusterID" value:"065d7a87-b64f-4d80-9d60-46a1598ff07d" > parameters:<key:"csi.storage.k8s.io/pv/name" value:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" > parameters:<key:"csi.storage.k8s.io/pvc/name" value:"raw-block-pvc" > parameters:<key:"csi.storage.k8s.io/pvc/namespace" value:"kube-system" > parameters:<key:"pool" value:"kubernetes" > secrets:<key:"userID" value:"kubernetes" > secrets:<key:"userKey" value:"hbbb" > 
I0327 14:46:01.753418       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:01.753543       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0327 14:46:01.757720       1 connection.go:185] GRPC response: {}
I0327 14:46:01.757860       1 connection.go:186] GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:01.757940       1 controller.go:752] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:01.758088       1 controller.go:1099] Final error received, removing PVC 135cf774-db66-4d34-9d29-654d6527bb16 from claims in progress
W0327 14:46:01.758145       1 controller.go:958] Retrying syncing claim "135cf774-db66-4d34-9d29-654d6527bb16", failure 1
E0327 14:46:01.758245       1 controller.go:981] error syncing claim "135cf774-db66-4d34-9d29-654d6527bb16": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:01.758316       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:02.244206       1 controller.go:1332] provision "kube-system/raw-block-pvc" class "csi-rbd-sc": started
I0327 14:46:02.244777       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/raw-block-pvc"
I0327 14:46:02.253676       1 controller.go:731] CreateVolumeRequest name:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" capacity_range:<required_bytes:1073741824 > volume_capabilities:<block:<> access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"clusterID" value:"065d7a87-b64f-4d80-9d60-46a1598ff07d" > parameters:<key:"csi.storage.k8s.io/pv/name" value:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" > parameters:<key:"csi.storage.k8s.io/pvc/name" value:"raw-block-pvc" > parameters:<key:"csi.storage.k8s.io/pvc/namespace" value:"kube-system" > parameters:<key:"pool" value:"kubernetes" > secrets:<key:"userID" value:"kubernetes" > secrets:<key:"userKey" value:"" > 
I0327 14:46:02.253939       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:02.253978       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0327 14:46:02.256666       1 connection.go:185] GRPC response: {}
I0327 14:46:02.256778       1 connection.go:186] GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:02.256841       1 controller.go:752] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:02.256934       1 controller.go:1099] Final error received, removing PVC 135cf774-db66-4d34-9d29-654d6527bb16 from claims in progress
W0327 14:46:02.256986       1 controller.go:958] Retrying syncing claim "135cf774-db66-4d34-9d29-654d6527bb16", failure 2
E0327 14:46:02.257034       1 controller.go:981] error syncing claim "135cf774-db66-4d34-9d29-654d6527bb16": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:02.257100       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:04.080642       1 leaderelection.go:273] successfully renewed lease kube-system/rbd-csi-ceph-com
I0327 14:46:04.257524       1 controller.go:1332] provision "kube-system/raw-block-pvc" class "csi-rbd-sc": started
I0327 14:46:04.258083       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/raw-block-pvc"
I0327 14:46:04.266789       1 controller.go:731] CreateVolumeRequest name:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" capacity_range:<required_bytes:1073741824 > volume_capabilities:<block:<> access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"clusterID" value:"065d7a87-b64f-4d80-9d60-46a1598ff07d" > parameters:<key:"csi.storage.k8s.io/pv/name" value:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" > parameters:<key:"csi.storage.k8s.io/pvc/name" value:"raw-block-pvc" > parameters:<key:"csi.storage.k8s.io/pvc/namespace" value:"kube-system" > parameters:<key:"pool" value:"kubernetes" > secrets:<key:"userID" value:"kubernetes" > secrets:<key:"userKey" value:"" > 
I0327 14:46:04.267108       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:04.267183       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0327 14:46:04.269893       1 connection.go:185] GRPC response: {}
I0327 14:46:04.269987       1 connection.go:186] GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:04.270046       1 controller.go:752] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:04.270158       1 controller.go:1099] Final error received, removing PVC 135cf774-db66-4d34-9d29-654d6527bb16 from claims in progress
W0327 14:46:04.270192       1 controller.go:958] Retrying syncing claim "135cf774-db66-4d34-9d29-654d6527bb16", failure 3
E0327 14:46:04.270239       1 controller.go:981] error syncing claim "135cf774-db66-4d34-9d29-654d6527bb16": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:04.270295       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:08.270752       1 controller.go:1332] provision "kube-system/raw-block-pvc" class "csi-rbd-sc": started
I0327 14:46:08.271364       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/raw-block-pvc"
I0327 14:46:08.282387       1 controller.go:731] CreateVolumeRequest name:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" capacity_range:<required_bytes:1073741824 > volume_capabilities:<block:<> access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"clusterID" value:"065d7a87-b64f-4d80-9d60-46a1598ff07d" > parameters:<key:"csi.storage.k8s.io/pv/name" value:"pvc-135cf774-db66-4d34-9d29-654d6527bb16" > parameters:<key:"csi.storage.k8s.io/pvc/name" value:"raw-block-pvc" > parameters:<key:"csi.storage.k8s.io/pvc/namespace" value:"kube-system" > parameters:<key:"pool" value:"kubernetes" > secrets:<key:"userID" value:"kubernetes" > secrets:<key:"userKey" value:"" > 
I0327 14:46:08.282616       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:08.282644       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0327 14:46:08.285820       1 connection.go:185] GRPC response: {}
I0327 14:46:08.285979       1 connection.go:186] GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:08.286049       1 controller.go:752] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:08.286167       1 controller.go:1099] Final error received, removing PVC 135cf774-db66-4d34-9d29-654d6527bb16 from claims in progress
W0327 14:46:08.286224       1 controller.go:958] Retrying syncing claim "135cf774-db66-4d34-9d29-654d6527bb16", failure 4
E0327 14:46:08.286281       1 controller.go:981] error syncing claim "135cf774-db66-4d34-9d29-654d6527bb16": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:08.286336       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"raw-block-pvc", UID:"135cf774-db66-4d34-9d29-654d6527bb16", APIVersion:"v1", ResourceVersion:"27458", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:09.135215       1 leaderelection.go:273] successfully renewed lease kube-system/rbd-csi-ceph-com

csi-provisioner:

pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
E0327 14:46:01.757179       1 rbd_util.go:918] ID: 34 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 failed to validate image features invalid feature 
E0327 14:46:01.757300       1 utils.go:136] ID: 34 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:02.255285       1 utils.go:132] ID: 35 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:02.255594       1 utils.go:133] ID: 35 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
E0327 14:46:02.256074       1 rbd_util.go:918] ID: 35 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 failed to validate image features invalid feature 
E0327 14:46:02.256195       1 utils.go:136] ID: 35 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:04.268457       1 utils.go:132] ID: 36 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:04.268765       1 utils.go:133] ID: 36 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
E0327 14:46:04.269244       1 rbd_util.go:918] ID: 36 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 failed to validate image features invalid feature 
E0327 14:46:04.269381       1 utils.go:136] ID: 36 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:08.283931       1 utils.go:132] ID: 37 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:08.284445       1 utils.go:133] ID: 37 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
E0327 14:46:08.285020       1 rbd_util.go:918] ID: 37 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 failed to validate image features invalid feature 
E0327 14:46:08.285191       1 utils.go:136] ID: 37 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:12.637580       1 utils.go:132] ID: 38 GRPC call: /csi.v1.Identity/Probe
I0327 14:46:12.637774       1 utils.go:133] ID: 38 GRPC request: {}
I0327 14:46:12.637867       1 utils.go:138] ID: 38 GRPC response: {}
I0327 14:46:16.298944       1 utils.go:132] ID: 39 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:16.299271       1 utils.go:133] ID: 39 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
E0327 14:46:16.299676       1 rbd_util.go:918] ID: 39 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 failed to validate image features invalid feature 
E0327 14:46:16.299781       1 utils.go:136] ID: 39 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC error: rpc error: code = InvalidArgument desc = invalid feature 
I0327 14:46:32.319078       1 utils.go:132] ID: 40 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC call: /csi.v1.Controller/CreateVolume
I0327 14:46:32.319416       1 utils.go:133] ID: 40 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","parameters":{"clusterID":"065d7a87-b64f-4d80-9d60-46a1598ff07d","csi.storage.k8s.io/pv/name":"pvc-135cf774-db66-4d34-9d29-654d6527bb16","csi.storage.k8s.io/pvc/name":"raw-block-pvc","csi.storage.k8s.io/pvc/namespace":"kube-system","pool":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
E0327 14:46:32.319845       1 rbd_util.go:918] ID: 40 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 failed to validate image features invalid feature 
E0327 14:46:32.319964       1 utils.go:136] ID: 40 Req-ID: pvc-135cf774-db66-4d34-9d29-654d6527bb16 GRPC error: rpc error: code = InvalidArgument desc = invalid feature

**Comment by nixpanic** [comment]
Hi,

can you make sure you have the `imageFeatures` option in your StorageClass, similar to the example:

https://github.com/ceph/ceph-csi/blob/devel/examples/rbd/storageclass.yaml#L35-L39

**Comment by umitgunduz** [comment]
Hello, we are getting a similar error. The error is as follows.

```log I0329 17:33:24.066095 1393084 utils.go:133] ID: 848 GRPC request: {}
I0329 17:33:24.066293 1393084 utils.go:138] ID: 848 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I0329 17:33:24.070625 1393084 utils.go:132] ID: 849 Req-ID: 0001-0024-3e1c7396-6633-46a7-af70-7831955e6b55-0000000000000011-606affe5-7b89-11eb-821b-ea0501505127 GRPC call: /csi.v1.Node/NodeStageVolume
I0329 17:33:24.070844 1393084 utils.go:133] ID: 849 Req-ID: 0001-0024-3e1c7396-6633-46a7-af70-7831955e6b55-0000000000000011-606affe5-7b89-11eb-821b-ea0501505127 GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-9e622e08-357a-4f79-8ca4-cf967dc7c2b0/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["discard"]}},"access_mode":{"mode":1}},"volume_context":{"clusterID":"3e1c7396-6633-46a7-af70-7831955e6b55","csi.storage.k8s.io/pv/name":"pvc-9e622e08-357a-4f79-8ca4-cf967dc7c2b0","csi.storage.k8s.io/pvc/name":"redis-data-dev-redis-cluster-slave-0","csi.storage.k8s.io/pvc/namespace":"database","imageName":"csi-vol-606affe5-7b89-11eb-821b-ea0501505127","journalPool":"DEV-DATA","pool":"DEV-DATA","radosNamespace":"","storage.kubernetes.io/csiProvisionerIdentity":"1614172560433-8081-rbd.csi.ceph.com"},"volume_id":"0001-0024-3e1c7396-6633-46a7-af70-7831955e6b55-0000000000000011-606affe5-7b89-11eb-821b-ea0501505127"}
E0329 17:33:24.071055 1393084 rbd_util.go:918] ID: 849 Req-ID: 0001-0024-3e1c7396-6633-46a7-af70-7831955e6b55-0000000000000011-606affe5-7b89-11eb-821b-ea0501505127 failed to validate image features invalid feature 
E0329 17:33:24.071110 1393084 utils.go:136] ID: 849 Req-ID: 0001-0024-3e1c7396-6633-46a7-af70-7831955e6b55-0000000000000011-606affe5-7b89-11eb-821b-ea0501505127 GRPC error: rpc error: code = Internal desc = invalid feature ```

**Comment by hodolomax** [comment]
Hello, I had same problem like yours. In my csi-rbdplugin deployment, csi images was canary build (quay.io/cephcsi/cephcsi:canary). Then I changed it latest stable version v3.2.1 (quay.io/cephcsi/cephcsi:v3.2.1) (release list here https://quay.io/repository/cephcsi/cephcsi?tag=canary&tab=tags) After that my kubernetes cluster start working correctly with ceph drivers. 

example csi-rbdplugin daemonset yaml below:

```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-rbdplugin
spec:
  selector:
    matchLabels:
      app: csi-rbdplugin
  template:
    metadata:
      labels:
        app: csi-rbdplugin
    spec:
      serviceAccount: rbd-csi-nodeplugin
      hostNetwork: true
      hostPID: true
      # to use e.g. Rook orchestrated cluster, and mons' FQDN is
      # resolved through k8s service, set dns policy to cluster first
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: driver-registrar
          # This is necessary only for systems with SELinux, where
          # non-privileged sidecar containers cannot access unix domain socket
          # created by privileged CSI driver container.
          securityContext:
            privileged: true
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/rbd.csi.ceph.com/csi.sock"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: csi-rbdplugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          # for stable functionality replace canary with latest release version
          image: quay.io/cephcsi/cephcsi:v3.2.1
          args:
            - "--nodeid=$(NODE_ID)"
            - "--type=rbd"
            - "--nodeserver=true"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--v=5"
            - "--drivername=rbd.csi.ceph.com"
            # If topology based provisioning is desired, configure required
            # node labels representing the nodes topology domain
            # and pass the label names below, for CSI to consume and advertise
            # its equivalent topology domain
            # - "--domainlabels=failure-domain/region,failure-domain/zone"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # - name: POD_NAMESPACE
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: spec.namespace
            # - name: KMS_CONFIGMAP_NAME
            #   value: encryptionConfig
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - mountPath: /dev
              name: host-dev
            - mountPath: /sys
              name: host-sys
            - mountPath: /run/mount
              name: host-mount
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - name: ceph-csi-config
              mountPath: /etc/ceph-csi-config/
            - name: ceph-csi-encryption-kms-config
              mountPath: /etc/ceph-csi-encryption-kms-config/
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins
              mountPropagation: "Bidirectional"
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: keys-tmp-dir
              mountPath: /tmp/csi/keys
        - name: liveness-prometheus
          securityContext:
            privileged: true
          image: quay.io/cephcsi/cephcsi:v3.2.1
          args:
            - "--type=liveness"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--metricsport=8680"
            - "--metricspath=/metrics"
            - "--polltime=60s"
            - "--timeout=3s"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          imagePullPolicy: "IfNotPresent"
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/rbd.csi.ceph.com
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins
            type: Directory
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-mount
          hostPath:
            path: /run/mount
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: ceph-csi-config
          configMap:
            name: ceph-csi-config
        - name: ceph-csi-encryption-kms-config
          configMap:
            name: ceph-csi-encryption-kms-config
        - name: keys-tmp-dir
          emptyDir: {
            medium: "Memory"
          }
```
