### ISSUE TITLE
[csi-rbd] Support erasure coded pools

### ISSUE THREAD

**Issue by lbogdan** [ceph/ceph-csi#199]
As suggested by @travisn, I'm opening this to track a feature gap between the rook RBD volume provisioner and the ceph CSI RBD plugin:

From what I could gather from the [source](https://github.com/ceph/ceph-csi/blob/master/pkg/rbd/rbd_util.go#L138), when defining a `StorageClass`, the plugin only supports specifying a single pool, which will be sent as `--pool` argument to `rbd create`.
But, in order to be able to use erasure coded pools with RBD, you also need to send `--data-pool`, as described [here](http://docs.ceph.com/docs/mimic/rados/operations/erasure-code/#erasure-coding-with-overwrites).
Rook allows you to specify both the replicated metadata and the erasure coded data pool, as documented [here](https://github.com/rook/rook/blob/master/Documentation/ceph-block.md#advanced-example-erasure-coded-block-storage):
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
...
parameters:
  blockPool: replicated-metadata-pool
  dataBlockPool: ec-data-pool
```
