### ISSUE TITLE
Creating PVC from rbd snapshots

### ISSUE THREAD

**Issue by kuhar2007** [ceph/ceph-csi#2031]
# Describe the feature you'd like to have #

We have snapshots in ceph cluster (pool/image@snap1).
Maybe you can add functional when provisioner will clone image from this snapshot, create PV with this image and bound it to PVC.
Commands at ceph cluster:
`rbd clone pool/image@snap1 pool/image-clone`

It will be good, if it will work with encryption. 

# What is the value to the end user? (why is it a priority?) #

We can set which snapshot we can use at pvc, for example:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: "pvc-name"
   labels:
     image: "image"
     snapshot: "snap1"
 spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 10G
   storageClassName: csi-rbd-sc 
```

# How will we know we have a good solution? (acceptance criteria) #

* PVC was create from rbd snapshot
* PVC have same data as at snapshot in ceph cluster(pool/image@snap1)
