### ISSUE TITLE
Mountoptions seems not to be passed correctly while mounting pre-provisioned volumes

### ISSUE THREAD

**Issue by YingshuoTao** [ceph/ceph-csi#2114]
# Describe the bug #
Mountoptions (kernelMountOptions/fuseMountOptions) seemed not to be passed into spec.csi.volumeAttributes.

# Environment details #
- Image/version of Ceph CSI driver : 3.3.1
- Helm chart version : 3.3.1-canary
- Kernel version : 5.3.0-53
- Mounter used for mounting PVC: fuse & kernel
- Kubernetes cluster version : 1.18.2
- Ceph cluster version : 16.2.4

# Steps to reproduce #
Deploy a pod using pre-provisioned volumes like below
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pre-provisioned-static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: pre-provisioned-static-pv
    readOnly: false
    fsType: ext4
    volumeAttributes:
      clusterID: xxxxxx
      fsName: cephfs
      staticVolume: true
      rootPath: /path/to/root
      mounter: kernel (fuse)
      kernelMountOptions (fuseMountOptions): noatime,...
    nodeStageSecretRef:
      name: cephfs-secret
      namespace: ceph-csi-cephfs
```

# Actual results #
The extra mountoptions didn't work.

# Expected behavior #
The extra mountoptions in spec.csi.volumeAttributes definition would work.

# Personal thoughts #
I took a look the code, and found that the expected mountOptions are not merged into "opts" in function 'newVolumeOptionsFromStaticVolume' in [volumeoptions.go](https://github.com/ceph/ceph-csi/blob/devel/internal/cephfs/volumeoptions.go).
Is this the right entry of mounting pre-provisioned volumes and is an expected behavior?
Sorry I'm not familiar with golang, any help would be greatly appreciated!
