### ISSUE TITLE
Add clusterID and poolID configuration to support failover in Regional DR

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2118]
```0001-0009-rook-ceph-0000000000000002-b0285c97-a0ce-11eb-8c66-0242ac110002```

The Above is the volumeID is sent back in the response to the CreateVolume operation and will be added as a volume handle in the PV spec. CO (Kubernetes) uses above as the identifier for further operations on the volume/PVC. 

The VolumeID is encoded as below

```
0001 -->	                         [csi_id_version=1:4byte] + [-:1byte]
0009 -->	                          [length of clusterID=1:4byte] + [-:1byte]
rook-ceph -->	                          [clusterID:36bytes (MAX)] + [-:1byte]
0000000000000002 -->	                  [poolID:16bytes] + [-:1byte]
b0285c97-a0ce-11eb-8c66-0242ac110002 --> [ObjectUUID:36bytes]

Total of constant field lengths, including '-' field separators would hence be,
4+1+4+1+1+16+1+36 = 64
```

When mirroring is enabled the volume which is `csi-vol-ObjectUUID` is mirrored to the other cluster.

> `csi-vol` is const name and over has the option to override it in storageclass.

 During the Disaster Recovery (failover operation) the PVC and PV will be recreated on the other cluster when cephcsi receives the request for operations like (NodeStage, ExpandVolume, DeleteVolume, etc) the volumeId is sent in the request which will help to identify the volume.

```yaml=
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
       "clusterID": "rook-ceph",
        "radosNamespace": "<rados-namespace>",
        "monitors": [
          "192.168.39.82:6789"
        ],
        "cephFS": {
          "subvolumeGroup": "<subvolumegroup for cephfs volumes>"
        }
      },
            {
       "clusterID": "fs-id",
        "radosNamespace": "<rados-namespace>",
        "monitors": [
          "192.168.39.83:6789"
        ],
        "cephFS": {
          "subvolumeGroup": "<subvolumegroup for cephfs volumes>"
        }
      }
    ]
metadata:
  name: ceph-csi-config
```

During CSI operations, CephCSI will decode the volumeID and gets the monitor configuration from the configmap, and from the pool ID it will get the pool Name and retrieves the OMAP data stored in the rados OMAP, and finally checks the volume is present in that pool.

We have two below problems here

* The clusterID can be different
    * as the clusterID is the namespace where rook is deployed, the Rook might be deployed in a different namespace on the secondary cluster
    * In standalone cephcsi the clusterID is fs ID. and fs ID is unique per cluster

* The poolID can be different
    * Pools ID which is encoded in the volumeID won't remain the same across clusters
