### ISSUE TITLE
Cant't mount staticVolume 

### ISSUE THREAD

**Issue by rsoika** [ceph/ceph-csi#2157]
I have installed ceph-csi v3.2 in my kubernetes cluster from [here](https://github.com/ceph/ceph-csi/tree/release-v3.2)

My storage class looks like this:

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph
provisioner: rbd.csi.ceph.com
parameters:
   clusterID: a1d43460-xxxxxxxxxxxxxxxxxxxxxxxxxxx
   pool: kubernetes
   imageFeatures: layering
   csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
   csi.storage.k8s.io/provisioner-secret-namespace: ceph-system
   csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
   csi.storage.k8s.io/controller-expand-secret-namespace: ceph-system
   csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
   csi.storage.k8s.io/node-stage-secret-namespace: ceph-system
   csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
   - discard
```

Everything works fine if I am using dynamic volume claims like this:

```

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph
---
apiVersion: v1
kind: Pod
metadata:
  name: csi-rbd-demo-pod
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: rbd-pvc
        readOnly: false
```

But what I need for my static application is a static volume. From the [documentation](https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md), I first  create a image on my ceph cluster (octopus) with the command: 

`# rbd create demo-internal-index --size=1024 --pool=kubernetes --image-feature layering`

Than I create the following PersistentVolumeClaim and PersistentVolumeClaim as explained

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: index
  namespace: office-demo-internal
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: demo-internal-index
  storageClassName: ceph
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-internal-index
spec:
  volumeMode: Filesystem
  storageClassName: ceph
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    #mountOptions:
    #  - discard
    driver: rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: csi-rbd-secret
      namespace: ceph-system
    volumeAttributes:
      clusterID: "a1d43460-xxxxxxxxxxxxxxxxxxxxxxxxxxx"
      pool: "kubernetes"
      staticVolume: "true"
      imageFeatures: "layering"
      #mounter: rbd-nbd
    volumeHandle: "demo-internal-imixs"
```

This Setup works on the first deployment. If I delete the POD and try to redeploy it, the deployment stucks. 

I got the following deployment events:

```
| Events:                                                                                                                                                                                             │
│   Type     Reason            Age                From                     Message                                                                                                                    │
│   ----     ------            ----               ----                     -------                                                                                                                    │
│   Warning  FailedScheduling  29s                default-scheduler        0/4 nodes are available: 4 persistentvolumeclaim "index" not found.                                                        │
│   Warning  FailedScheduling  25s (x3 over 29s)  default-scheduler        0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims.                                               │
│   Normal   Scheduled         11s                default-scheduler        Successfully assigned office-demo-internal/imixs-documents-7c6c86466b-sqbmt to tikal-worker-3                              │
│   Warning  FailedMount       3s (x5 over 11s)   kubelet, tikal-worker-3  MountVolume.SetUp failed for volume "demo-internal-index" : rpc error: code = Internal desc = mount failed: exit status 32 │
│ Mounting command: mount                                                                                                                                                                             │
│ Mounting arguments: -t ext4 -o bind,_netdev /var/lib/kubelet/plugins/kubernetes.io/csi/pv/demo-internal-index/globalmount/demo-internal-imixs /var/lib/kubelet/pods/af2f33e0-06da-4429-9f75-908981c │
│ b85c3/volumes/kubernetes.io~csi/demo-internal-index/mount                                                                                                                                           │
│ Output: mount: /var/lib/kubelet/pods/af2f33e0-06da-4429-9f75-908981cb85c3/volumes/kubernetes.io~csi/demo-internal-index/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/demo-in │
│ ternal-index/globalmount/demo-internal-imixs does not exist. 
``` 

And the csi-plugin log looks like this:

```
 csi-rbdplugin I0613 15:56:55.777673   32379 utils.go:132] ID: 32 GRPC call: /csi.v1.Node/NodeGetCapabilities                                                                                          
 csi-rbdplugin I0613 15:56:55.777804   32379 utils.go:133] ID: 32 GRPC request: {}                                                                                                                     
 csi-rbdplugin I0613 15:56:55.777944   32379 utils.go:138] ID: 32 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}                
 csi-rbdplugin I0613 15:56:55.783115   32379 utils.go:132] ID: 33 Req-ID: demo-internal-imixs GRPC call: /csi.v1.Node/NodePublishVolume                                                                
 csi-rbdplugin I0613 15:56:55.783340   32379 utils.go:133] ID: 33 Req-ID: demo-internal-imixs GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/demo-internal-index/ 
 globalmount","target_path":"/var/lib/kubelet/pods/af2f33e0-06da-4429-9f75-908981cb85c3/volumes/kubernetes.io~csi/demo-internal-index/mount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ex 
 t4"}},"access_mode":{"mode":1}},"volume_context":{"clusterID":"a1d43460-cc45-11eb-a7bd-960000bd038e","imageFeatures":"layering","pool":"kubernetes","staticVolume":"true"},"volume_id":"demo-internal 
 -imixs"}                                                                                                                                                                                              
 csi-rbdplugin I0613 15:56:55.783525   32379 nodeserver.go:518] ID: 33 Req-ID: demo-internal-imixs target /var/lib/kubelet/pods/af2f33e0-06da-4429-9f75-908981cb85c3/volumes/kubernetes.io~csi/demo-in 
 ternal-index/mount                                                                                                                                                                                    
 csi-rbdplugin isBlock false                                                                                                                                                                           
 csi-rbdplugin fstype ext4                                                                                                                                                                             
 csi-rbdplugin stagingPath /var/lib/kubelet/plugins/kubernetes.io/csi/pv/demo-internal-index/globalmount/demo-internal-imixs                                                                           
 csi-rbdplugin readonly false                                                                                                                                                                          
 csi-rbdplugin mountflags [bind _netdev]                                                                                                                                                               
 csi-rbdplugin E0613 15:56:55.814344   32379 mount_linux.go:150] Mount failed: exit status 32                                                                                                          
 csi-rbdplugin Mounting command: mount                                                                                                                                                                 
 csi-rbdplugin Mounting arguments: -t ext4 -o bind,_netdev /var/lib/kubelet/plugins/kubernetes.io/csi/pv/demo-internal-index/globalmount/demo-internal-imixs /var/lib/kubelet/pods/af2f33e0-06da-4429- 
 9f75-908981cb85c3/volumes/kubernetes.io~csi/demo-internal-index/mount                                                                                                                                 
 csi-rbdplugin Output: mount: /var/lib/kubelet/pods/af2f33e0-06da-4429-9f75-908981cb85c3/volumes/kubernetes.io~csi/demo-internal-index/mount: special device /var/lib/kubelet/plugins/kubernetes.io/cs 
 i/pv/demo-internal-index/globalmount/demo-internal-imixs does not exist.                                                                                                                              
 csi-rbdplugin E0613 15:56:55.814449   32379 utils.go:136] ID: 33 Req-ID: demo-internal-imixs GRPC error: rpc error: code = Internal desc = mount failed: exit status 32                               
 csi-rbdplugin Mounting command: mount                                                                                                                                                                 
 csi-rbdplugin Mounting arguments: -t ext4 -o bind,_netdev /var/lib/kubelet/plugins/kubernetes.io/csi/pv/demo-internal-index/globalmount/demo-internal-imixs /var/lib/kubelet/pods/af2f33e0-06da-4429- 
 9f75-908981cb85c3/volumes/kubernetes.io~csi/demo-internal-index/mount                                                                                                                                 
 csi-rbdplugin Output: mount: /var/lib/kubelet/pods/af2f33e0-06da-4429-9f75-908981cb85c3/volumes/kubernetes.io~csi/demo-internal-index/mount: special device /var/lib/kubelet/plugins/kubernetes.io/cs 
 i/pv/demo-internal-index/globalmount/demo-internal-imixs does not exist.   
```

I can't see what I did wrong. How can I provide more information to narrow down the problem?
