### ISSUE TITLE
StorageClass for staticVolume

### ISSUE THREAD

**Issue by rsoika** [ceph/ceph-csi#2299]
# Describe the feature you'd like to have #

I am not sure if my question/feature request is valid or still exists. It is about the usage of static volumes.

I am running the Ceph ceph-csi plugin and provisioner in version 3.3.1 within my Kubernetes cluster. Everything works grate (Thanks for your work!)

To define a static volume I currently do the following

1.) I create in my ceph cluster an image:

     rbd create my-dbdata --size=1024 --pool=kubernetes --image-feature layering

2) than I create in my kubernetes Deployment a PersistenceVolume :

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-dbdata
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: csi-rbd-secret
      namespace: ceph-system
    volumeAttributes:
      "clusterID": "1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      "pool": "kubernetes"
      "staticVolume": "true"
      "imageFeatures": "layering"
    volumeHandle: "my-dbdata"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```

Why can't I (as an cluster admin) simply define a storage class with the csi cluster data

```
  csi:
    driver: rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: csi-rbd-secret
      namespace: ceph-system
    volumeAttributes:
      "clusterID": "1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      "pool": "kubernetes"
      "staticVolume": "true"
      "imageFeatures": "layering"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

```

...and than reduce my PersitenceVolume to a more simple config:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-dbdata
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: ceph-durable
  csi:
    volumeHandle: "my-dbdata"
```

This would simplify the deployment in case you have many PersistenceVolumes running on a ceph cluster
