### ISSUE TITLE
resize RBD static PVC

### ISSUE THREAD

**Issue by rsoika** [ceph/ceph-csi#2552]
I am using RBD static PVCs in my Kubernetes Cluster. Everything works fine so far.

Today I stumbled into the problem that my PV was to small and I resized it in ceph.
But I did not recognized that resizing is not yet supported by the ceph-csi plugin as stated on this page:
https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md

My question is: are there any plans to support this feature. Or do you have any guideline how I should deal with the case when I need to expand my static volume. I expected that I can help myself with running the resize2fs command from within the POD after resizing the image but this did not work.

To make it more clear: I was of course able to expand my RBD Image within Ceph (from 30 GiB to 70 GiB). But after reconfiguring my PVC/PV and restarting the POD in Kubernetes, the POD still showed the /dev/rbd1 with 30GiB 

My Configuraiton in Kubernetes looks lie this:

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata2
  namespace: abc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 70Gi
  volumeMode: Filesystem
  volumeName: "dbdata2"


---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: dbdata2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 70Gi
  csi:
    driver: rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: csi-rbd-secret
      namespace: ceph-system
    volumeAttributes:
      "clusterID": "13xxxxxxxxxxxxxxxxxxxxxxxe"
      "pool": "kubernetes"
      "staticVolume": "true"
      # The imageFeatures must match the created ceph image exactly!!!
      "imageFeatures": "layering"
    volumeHandle: "dbdata2"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```

**Comment by Madhu-1** [comment]
For now, AFAIK you can go and resize the filesystem on the rbdplugin for now.

The fix for this one is
* Check the filesystem created for rbd block device\
* check the size and compare it with the rbd image
* If resize is required do it

and this also might help for allowing PVC-PVC clone to higher size and PVC created from snapshot also.

**Comment by rsoika** [comment]
Thanks for your response. When I check the size within my POD I can see that the new size is not assigned to the device.
 
With '_If resize is required do it_', do you mean I should use the `resize2fs` command?

**Comment by nixpanic** [comment]
Yes, you would need to run `resize2fs` to update the metadata in the ext4 filesystem to reflect the new rbd image size. You can run this command from the csi-rbdplugin container from the daemonset on the node where the rbd image is mapped (and the Pod using the PVC is running).

**Comment by rsoika** [comment]
Ok, I found an additional hint [here](https://github.com/rook/rook/issues/3133#issuecomment-501675614) which helps me to understand the procedure.

It seems that my main problem was, that in my Postgres Container I did not set the flag '`securityContext.privileged:true`'

     .....
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: dbdata
          subPath: postgres
        securityContext:
          privileged: true
     ....

After doing so, I was able to simply ssh into my Postgres POD and running the `resize2fs` command:

```
root@postgres-59f8bdfc99-29ll6:/# resize2fs /dev/rbd16
resize2fs 1.43.4 (31-Jan-2017)
Filesystem at /dev/rbd16 is mounted on /var/lib/postgresql/data; on-line resizing required
old_desc_blocks = 1, new_desc_blocks = 1
The filesystem on /dev/rbd16 is now 524288 (4k) blocks long.
```

It looks that now my POD behaves exactly as I expect and shows the new disk space 

I think you don't need to use the csi-rbdplugin container for that operation. You just need to figure out the correct device number of the RBD device mounted in your container. 

What is your opinion about this procedure? Would it be more elegant to use a kubernetes job object as in [this example](https://pastebin.com/viKFsdW5)?

And would it be worse to write a short example into this [doc page](https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md)?

Something like:

# Resize RBD static PV

If you resize your Ceph Image later, you also need to update the ext4 fs. This can be done with the command

    # resize2fs /dev/rbd[number]

Where you need to replace [number] with the correct rbd image mounted within your POD. 

Or you can run the following kubernetes job mounting the corresponding image and resizing it automatically. 

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: debian-disk-resize
spec:
  template:
    spec:
      containers:
        - name: debian
          image: debian
          command:
            - resize2fs
            - /dev/rbd0
          volumeMounts:
            - name: volume-to-resize
              mountPath: /var/lib/datas-restore
          securityContext:
            privileged: true
      volumes:
        - name: volume-to-resize
          persistentVolumeClaim:
            claimName: [claim name to resize]
      restartPolicy: Never
```
...........

**Comment by nixpanic** [comment]
Adding the steps to resize a static PV seems reasonable to me. Feel free to send a PR for that :+1:

**Comment by Madhu-1** [comment]
> Adding the steps to resize a static PV seems reasonable to me. Feel free to send a PR for that +1

already working on this one, will send a  PR soon

**Comment by rsoika** [comment]
I have now tried to develop a king of generic JOB to resize an image. The only thing to specify here is the name of the PVC. 

```
---
###################################################
# This job can be used to resize a ext4 filesystme
# alligned to the given size of the underlying RBD image.
###################################################
apiVersion: batch/v1
kind: Job
metadata:
  name: ext4-resize2fs
spec:
  template:
    spec:
      containers:
        - name: debian
          image: debian

          command: ["/bin/sh"]
          args:
            - -c
            - >-
                echo '******** start resizeing block device  ********' &&
                echo ...find rbd mounts to be resized.... &&
                df | grep /rbd &&
                DEVICE=`df | grep /rbd | awk '{print $1}'` &&
                echo ...resizing device $DEVICE ... &&
                resize2fs $DEVICE &&
                echo '******** resize block device completed ********'

          volumeMounts:
            - name: volume-to-resize
              mountPath: /tmp/mount2resize
          securityContext:
            privileged: true
      volumes:
        - name: volume-to-resize
          persistentVolumeClaim:
            claimName: test-pg-dbdata
      restartPolicy: Never
  backoffLimit: 1
```


What did you think about this job?
