### ISSUE TITLE
Creation of RBD PV of existing image with full snapshot/clone/etc. functionality

### ISSUE THREAD

**Issue by dren-dk** [ceph/ceph-csi#2573]
# Describe the feature you'd like to have #

I have a number of large RBD images, some created with external provisioner, some by other means, that I'd like to use with ceph-csi, specifically so I can start using the snapshot/clone functionality.

Ideally I would just create a PV with a volumeHandle of my own choosing and the pool and imageName attributes needed to point to the image and have it work.

I have seen that a static PV can be created from scratch, but that the PV cannot be used for any of the quite useful, new things that CSI is supposed to offer: https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md

Is there any chance that static PVs can gain the ability to support the full set of features? (Why on earth not?)

I've been reading up on how ceph-csi uses omap to store the mapping from volumeHandle to image information:
https://www.mrajanna.com/tracking-pv-rados-omap-in-cephcsi/

Judging by persistentvolume.go there's code to regenerate the omap data from the pv.Spec.CSI.VolumeAttributes, and I think I understand how to generate a PV with valid data, including a volumeHandle, so I'm puzzled as to why creation of PVs has not been documented.

Was PV creation judged to be too gnarly or is there some sneaky detail that I'm missing?

# What is the value to the end user? (why is it a priority?) #

Users would be able to migrate any RBD images to be under ceph-csi control without creating new images and copying TBs of data while being off-line.

# How will we know we have a good solution? (acceptance criteria) #

When any existing RBD image (with compatible options) can be "adopted" by ceph-csi.

**Comment by dren-dk** [comment]
I have been digging around in the code and experimenting a bit with manually creating a PV, so far it seems to work with a PV that I modified to use a different image than the one ceph-csi created for me.

Generating the volumeHandle wasn't too bad, the prefix can be lifted from an existing PV and the last 36 chars must be the same as pv.spec.csi.volumeAttributes.imageName, which must be the rbd image that already exists, so "rbd mv" is need to make it conform, details of the required format is documented by the code here: https://github.com/ceph/ceph-csi/blob/devel/internal/util/volid.go

I found four quirks so far:
1: The image name prefix must be csi-vol- specifying an image with a different prefix doesn't work even if pv.spec.csi.volumeAttributes.volumeNamePrefix is specified and matches the image name, I suspect this is due to voljournal.go(707).

2: The part of the image name after the prefix must be exactly 36 chars, I just padded it with hex chars.

3: The omap key csi.imageid doesn't get populated, it's described as being needed to delete the image, there's no description of where that value comes from, but I can do without that, though.

4: The omap key csi.volume.owner doesn't get populated, it seems to contain the namespace of the PVC.

I'm not done digging through https://github.com/ceph/ceph-csi/blob/devel/internal/journal/voljournal.go but it seems to confirm that csi.imageid is only needed to delete the image.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rbd.csi.ceph.com
  finalizers:
  - kubernetes.io/pv-protection
  name: fest-hest
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: rbd-storage
    namespace: test-csi
  csi:
    controllerExpandSecretRef:
      name: csi-rbd-provisioner
      namespace: ceph-csi-rbd
    driver: rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: csi-rbd-node
      namespace: ceph-csi-rbd
    volumeAttributes:
      clusterID: ceph
      imageFeatures: layering
      imageName: csi-vol-fest-hest-712e5e9be23e3a9cb4a6d81878
      journalPool: kube
      pool: kube
      storage.kubernetes.io/csiProvisionerIdentity: 1634198207386-8081-rbd.csi.ceph.com
      thickProvision: "false"
    volumeHandle: 0001-0004-ceph-0000000000000009-fest-hest-712e5e9be23e3a9cb4a6d81878
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-rbd
  volumeMode: Filesystem

```
