### ISSUE TITLE
Add inline volume support for   Ceph CSI driver 

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2587]
# Describe the feature you'd like to have #

Traditionally, volumes that are backed by CSI drivers can only be used with a PersistentVolume and PersistentVolumeClaim object combination. Two different Kubernetes features allow volumes to follow the Pod's lifecycle: CSI ephemeral volumes and generic ephemeral volumes.

In both features, the volumes are specified directly in the pod specification for ephemeral use cases. At runtime, nested inline volumes follow the ephemeral lifecycle of their associated pods where Kubernetes and the driver handle all phases of volume operations as pods are created and destroyed.

CSI ephemeral Inline volume spec example:

```
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-inline-vol
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-inline-vol
      csi:
        driver: <drivername>
        volumeAttributes:
          something: something
```

General inline ephemeral support example:

```
kind: Pod
apiVersion: v1
metadata:
  name: some-pod
spec:
  containers:
     ...
  volumes:
    - name: scratch-volume
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: my-frontend-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "scratch-storage-class"
            resources:
              requests:
                storage: 1Gi
```

What new functionality do you want?

Add inline volume support for Ceph CSI driver

# What is the value to the end user? (why is it a priority?) #

The volume lifecycle can be controlled by the POD spec

# Additional context #

Design doc for the feature support has been captured here:
https://hackmd.io/SXcB4VizTKaI4E7efOV_xw
