### ISSUE TITLE
rbd: wrong dataPoolName restoring a snapshot from and erasure coded volume with topology constraint

### ISSUE THREAD

**Issue by tblgit** [ceph/ceph-csi#2925]
# Describe the bug #

Restoring  a snapshot with a new PVC results with a wrong dataPoolName in case of initial volume linked to a storageClass with topology constraints and erasure coding
The ceph image is created with a wrong datapool

# Environment details #

- Image/version of Ceph CSI driver : v3.5.1
- Helm chart version : ceph-csi-rbd-3
- Kernel version : 5.15.16
- Mounter used for mounting PVC: krbd
- Kubernetes cluster version : v1.22.7
- Ceph cluster version : 16.2.7

# Steps to reproduce #

1. Create a pvc using a storageClass with its topologyConstrainedPools
  ``` yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block-topology-ec
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  dataPool: repldefault-ec
  imageFeatures: layering
  imageFormat: "2"
  pool: repldefault
  topologyConstrainedPools: |
    [{"poolName":"poolzone1",
      "dataPool":"pool-zone1-ec",
      "domainSegments":[
        {"domainLabel":"zone","value":"zone1"}]},
     {"poolName":"poolzone2",
      "dataPool":"pool-zone2-ec",
      "domainSegments":[
        {"domainLabel":"zone","value":"zone2"}]},
     {"poolName":"poolzone3",
      "dataPool":"pool-zone3-ec",
      "domainSegments":[
        {"domainLabel":"zone","value":"zone3"}]}
    ]
provisioner: rook-ceph.rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```   

2. Create a pvc from this class and bind it to a pod, then check the ceph image pools

```
rbd info poolzone3/csi-vol-003ecb29-9e03-11ec-9133-929aa9899e2f

rbd image 'csi-vol-003ecb29-9e03-11ec-9133-929aa9899e2f':
	size 1 GiB in 256 objects
	order 22 (4 MiB objects)
	snapshot_count: 1
	id: 1587c346f5feb9
	data_pool: pool-zone3-ec
	block_name_prefix: rbd_data.6.1587c346f5feb9
	format: 2
	features: layering, data-pool, operations
	op_features: clone-parent, snap-trash
	flags: 
	create_timestamp: Mon Mar  7 10:40:26 2022
	access_timestamp: Mon Mar  7 10:40:26 2022
	modify_timestamp: Mon Mar  7 10:40:26 2022
```

3. Create a snapshot of this pvc

4. Create a pvc from the snapshot and bind it to a pod

# Actual results #

The new volume is created with the wrong dataPool which corresponds to the default dataPool received in the createVolume request (/csi.v1.Controller/CreateVolume). It is not overidden as it's done for the "pool" field

# Expected behavior #

The new volume/ceph image is created with same dataPool as the initial volume. 

# Logs #

- csi-provisioner logs

`
I0307 10:45:43.375652       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateVolume
I0307 10:45:43.375673       1 connection.go:184] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.rook-ceph.rbd.csi.ceph.com/zone":"zone3"}},{"segments":{"topology.rook-ceph.rbd.csi.ceph.com/zone":"zone2"}},{"segments":{"topology.rook-ceph.rbd.csi.ceph.com/zone":"zone1"}}],"requisite":[{"segments":{"topology.rook-ceph.rbd.csi.ceph.com/zone":"zone1"}},{"segments":{"topology.rook-ceph.rbd.csi.ceph.com/zone":"zone3"}},{"segments":{"topology.rook-ceph.rbd.csi.ceph.com/zone":"zone2"}}]},"capacity_range":{"required_bytes":1073741824},"name":"pvc-44559017-392e-4a25-8038-7148207117f6","parameters":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-44559017-392e-4a25-8038-7148207117f6","csi.storage.k8s.io/pvc/name":"pvc-test-ec-topo-restore","csi.storage.k8s.io/pvc/namespace":"test-snapshots","dataPool":"repldefault-ec","imageFeatures":"layering","imageFormat":"2","pool":"repldefault","topologyConstrainedPools":"[{\"poolName\":\"poolzone1\",\n  \"dataPool\":\"pool-zone1-ec\",\n  \"domainSegments\":[\n    {\"domainLabel\":\"zone\",\"value\":\"zone1\"}]},\n {\"poolName\":\"poolzone2\",\n  \"dataPool\":\"pool-zone2-ec\",\n  \"domainSegments\":[\n    {\"domainLabel\":\"zone\",\"value\":\"zone2\"}]},\n {\"poolName\":\"poolzone3\",\n  \"dataPool\":\"pool-zone3-ec\",\n  \"domainSegments\":[\n    {\"domainLabel\":\"zone\",\"value\":\"zone3\"}]}\n]\n"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}],"volume_content_source":{"Type":{"Snapshot":{"snapshot_id":"0001-0009-rook-ceph-0000000000000006-1e86231c-9e03-11ec-9133-929aa9899e2f"}}}}
I0307 10:45:44.127382       1 connection.go:186] GRPC response: {"volume":{"accessible_topology":[{"segments":{"topology.rook-ceph.rbd.csi.ceph.com/zone":"zone3"}}],"capacity_bytes":1073741824,"content_source":{"Type":{"Snapshot":{"snapshot_id":"0001-0009-rook-ceph-0000000000000006-1e86231c-9e03-11ec-9133-929aa9899e2f"}}},"volume_context":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-44559017-392e-4a25-8038-7148207117f6","csi.storage.k8s.io/pvc/name":"pvc-test-ec-topo-restore","csi.storage.k8s.io/pvc/namespace":"test-snapshots","dataPool":"repldefault-ec","imageFeatures":"layering","imageFormat":"2","imageName":"csi-vol-bd093c3d-9e03-11ec-9133-929aa9899e2f","journalPool":"repldefault","pool":"poolzone3","topologyConstrainedPools":"[{\"poolName\":\"poolzone1\",\n  \"dataPool\":\"pool-zone1-ec\",\n  \"domainSegments\":[\n    {\"domainLabel\":\"zone\",\"value\":\"zone1\"}]},\n {\"poolName\":\"poolzone2\",\n  \"dataPool\":\"pool-zone2-ec\",\n  \"domainSegments\":[\n    {\"domainLabel\":\"zone\",\"value\":\"zone2\"}]},\n {\"poolName\":\"poolzone3\",\n  \"dataPool\":\"pool-zone3-ec\",\n  \"domainSegments\":[\n    {\"domainLabel\":\"zone\",\"value\":\"zone3\"}]}\n]\n"},"volume_id":"0001-0009-rook-ceph-0000000000000006-bd093c3d-9e03-11ec-9133-929aa9899e2f"}}
I0307 10:45:44.127706       1 connection.go:187] GRPC error: <nil>
I0307 10:45:44.127723       1 controller.go:774] create volume rep: {CapacityBytes:1073741824 VolumeId:0001-0009-rook-ceph-0000000000000006-bd093c3d-9e03-11ec-9133-929aa9899e2f VolumeContext:map[clusterID:rook-ceph csi.storage.k8s.io/pv/name:pvc-44559017-392e-4a25-8038-7148207117f6 csi.storage.k8s.io/pvc/name:pvc-test-ec-topo-restore csi.storage.k8s.io/pvc/namespace:test-snapshots dataPool:repldefault-ec imageFeatures:layering imageFormat:2 imageName:csi-vol-bd093c3d-9e03-11ec-9133-929aa9899e2f journalPool:repldefault pool:poolzone3 topologyConstrainedPools:[{"poolName":"poolzone1",
  "dataPool":"pool-zone1-ec",
  "domainSegments":[
    {"domainLabel":"zone","value":"zone1"}]},
 {"poolName":"poolzone2",
  "dataPool":"pool-zone2-ec",
  "domainSegments":[
    {"domainLabel":"zone","value":"zone2"}]},
 {"poolName":"poolzone3",
  "dataPool":"pool-zone3-ec",
  "domainSegments":[
    {"domainLabel":"zone","value":"zone3"}]}
]
] ContentSource:snapshot:<snapshot_id:"0001-0009-rook-ceph-0000000000000006-1e86231c-9e03-11ec-9133-929aa9899e2f" >  AccessibleTopology:[segments:<key:"topology.rook-ceph.rbd.csi.ceph.com/zone" value:"zone3" > ] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0307 10:45:44.127885       1 controller.go:858] successfully created PV pvc-44559017-392e-4a25-8038-7148207117f6 for PVC pvc-test-ec-topo-restore and csi volume name 0001-0009-rook-ceph-0000000000000006-bd093c3d-9e03-11ec-9133-929aa9899e2f
`

# first analysis

The dataPool field is not overidden in function updateTopologyConstraints (rbd_journal.go)

<pre>
func updateTopologyConstraints(rbdVol *rbdVolume, rbdSnap *rbdSnapshot) error {
	var err error
	<b>if rbdSnap != nil {</b>
		// check if topology constraints matches snapshot pool
		rbdVol.Topology, err = util.MatchTopologyForPool(rbdVol.TopologyPools,
			rbdVol.TopologyRequirement, rbdSnap.Pool)
		if err != nil {
			return err
		}

		// update Pool, if it was topology constrained
		<b>if rbdVol.Topology != nil {
			rbdVol.Pool = rbdSnap.Pool
		}</b>

		return nil
	}
	// update request based on topology constrained parameters (if present)
	poolName, dataPoolName, topology, err := util.FindPoolAndTopology(rbdVol.TopologyPools, rbdVol.TopologyRequirement)
	if err != nil {
		return err
	}
	if poolName != "" {
		rbdVol.Pool = poolName
		rbdVol.DataPool = dataPoolName
		rbdVol.Topology = topology
	}

	return nil
}
</pre>
