### ISSUE TITLE
permission issue of CSI-VOL* directory 

### ISSUE THREAD

**Issue by dbenduga** [ceph/ceph-csi#3342]

**Comment by Madhu-1** [comment]
Please fill the template when creating an issue

**Comment by dbenduga** [comment]
by default csi-vol* directory permission is set to 755 due to that non-privileged user unable to write on it . If we changed it 777 working fine. I am using nautilus 14.2 22 ceph  

drwxr-xr-x 1 root root 2 Aug 24 12:05 csi-vol-0668bb95-23a5-11ed-9a40-02f7d0d81756
drwxr-xr-x 1 root root 2 Aug 24 12:01 csi-vol-83fcb0c4-23a4-11ed-9a40-02f7d0d81756

**Comment by Madhu-1** [comment]
setting 777 on both cephfs and rbd mounts are removed in cephcsi, Have you considered setting `SecurityContext:` in both pod spec and container spec? https://github.com/ceph/ceph-csi/blob/3ddec80346f6fe6ae6da8c19adfdb92e49e41fa8/e2e/utils.go#L515-L537

**Comment by dbenduga** [comment]
@Madhu-1 . Thanks for quick response.. Could you please share simple example of pod yaml file to use SecurityContext:

**Comment by dbenduga** [comment]
@Madhu-1 :  I am using below pod definition file  which is not working still directory is create by root user with 755 permission 

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: test123
  name: test123
spec:
  securityContext:
    runAsUser: 786
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - name: cephfs-pv-busybox
    image: busybox
    command: ["sleep", "60000"]
    volumeMounts:
    - mountPath: "/cephfs-pvc"
      name: cephfs-vol1
      readOnly: false
    securityContext:
      runAsUser: 786
      runAsGroup: 1000
  volumes:
  - name: cephfs-vol1
    persistentVolumeClaim:
      claimName: test1234

**Comment by Madhu-1** [comment]
```
---
apiVersion: v1
kind: Pod
metadata:
  name: csicephfs-demo-pod
spec:
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  containers:
    - name: web-server
      image: busybox
      command: ["sleep", "60000"]
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: cephfs-pvc
        readOnly: false
```
```
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: cephfs.csi.ceph.com
spec:
  attachRequired: false
  fsGroupPolicy: File
  podInfoOnMount: false
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent
```

with above csidriver object and the app pod should work

```
[🎩︎]mrajanna@fedora cephfs $]kubectl execectl exec -it csicephfs-demo-pod -- sh
/ $ whoami
whoami: unknown uid 1000
/ $ df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  27.9G      7.6G     18.6G  29% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     1.9G         0      1.9G   0% /sys/fs/cgroup
/dev/vda1                27.9G      7.6G     18.6G  29% /dev/termination-log
/dev/vda1                27.9G      7.6G     18.6G  29% /etc/resolv.conf
/dev/vda1                27.9G      7.6G     18.6G  29% /etc/hostname
/dev/vda1                27.9G      7.6G     18.6G  29% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
10.102.12.228:6789:/volumes/csi/csi-vol-14ea0695-0826-4741-8011-3278ad003a39/34b0e10c-9bd9-48a9-b05d-df91e5515c90
                          1.0G         0      1.0G   0% /var/lib/www/html
tmpfs                     3.8G     12.0K      3.8G   0% /var/run/secrets/kubernetes.io/serviceaccount
tmpfs                     1.9G         0      1.9G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                     1.9G         0      1.9G   0% /proc/scsi
tmpfs                     1.9G         0      1.9G   0% /sys/firmware
/ $ ll /var/lib/www/
sh: ll: not found
/ $ ls /var/lib/www/
html
/ $ ls -lrt /var/lib/www/
total 0
drwxrwsr-x    2 root     1000             1 Aug 24 15:02 html
/ $ ls -lrt /var/lib/www/html/
total 0
-rw-rw-r--    1 1000     1000             0 Aug 24 15:02 a
/ $ ls -lrt /var/lib/www/html/^C
/ $ cd /var/lib/www/html/
/var/lib/www/html $ ls
a
/var/lib/www/html $ touch b
/ $ ls -lrt /var/lib/www/html/
total 0
-rw-rw-r--    1 1000     1000             0 Aug 24 15:02 a
-rw-r--r--    1 1000     1000             0 Aug 24 15:05 b

```
