### ISSUE TITLE
API call not implemented server-side: No handler found for 'fs subvolume metadata set' in ceph 15.2.17

### ISSUE THREAD

**Issue by wanghongzhou** [ceph/ceph-csi#3347]
# Describe the bug #

failed to provision volume with StorageClass "csi-cephfs-sc": rpc error: code = Internal desc = failed to set metadata key "csi.storage.k8s.io/pvc/name", value "cephfs-pvc" on subvolume &{0xc000948160 a6893219-4fa6-437e-9de1-79c77c835fdb true 0xc0002f6648}: API call not implemented server-side: No handler found for 'fs subvolume metadata set'

# Environment details #

- Image/version of Ceph CSI driver : v3.7.0
- Kernel version : 5.4.210-1.el7.elrepo.x86_64
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : `kernel`
- Kubernetes cluster version : Server Version: v1.24.4
- Ceph cluster version : ceph version 15.2.17 (8a82819d84cf884bd39c17e3236e0632ac146dc4) octopus (stable)

# Additional context #

* csi-cephfs-secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  userID: cephfs
  userKey: AQBt1QNjlAEDJRAAWFeUCwOTLRcfDuok2dvejA==
  adminID: admin
  adminKey: AQBAmgNjcKxwGxAANjoDA2L12Ap403+qjB4tCA==
```
* csi-cephfs-sc.yaml
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-cephfs-sc
   namespace: ceph-csi
provisioner: cephfs.csi.ceph.com
parameters:
   clusterID: a6893219-4fa6-437e-9de1-79c77c835fdb
   fsName: cephfs
   pool: cehpfs-data
   mounter: kernel
   csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
   csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi
   csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
   csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi
   csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
   csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
 - discard
```
* csi-cephfs-test.yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-sc
```
```shell
[root@ceph-node-1 ~]# ceph --version
ceph version 15.2.17 (8a82819d84cf884bd39c17e3236e0632ac146dc4) octopus (stable)
[root@ceph-node-1 ~]# ceph mon --version
ceph version 15.2.17 (8a82819d84cf884bd39c17e3236e0632ac146dc4) octopus (stable)
[root@ceph-node-1 ~]# ceph mgr --version
ceph version 15.2.17 (8a82819d84cf884bd39c17e3236e0632ac146dc4) octopus (stable)
[root@ceph-node-1 ~]# ceph fs ls
name: cephfs, metadata pool: cehpfs-metadata, data pools: [cehpfs-data ]
[root@ceph-node-1 ~]# ceph auth get client.cephfs
exported keyring for client.cephfs
[client.cephfs]
        key = AQBt1QNjlAEDJRAAWFeUCwOTLRcfDuok2dvejA==
        caps mds = "allow rw"
        caps mgr = "allow rw"
        caps mon = "allow r"
        caps osd = "allow rw pool=cephfs-data, allow rw pool=cephfs-metadata"
[root@ceph-node-1 ~]# ceph auth get client.admin
exported keyring for client.admin
[client.admin]
        key = AQBAmgNjcKxwGxAANjoDA2L12Ap403+qjB4tCA==
        caps mds = "allow *"
        caps mgr = "allow *"
        caps mon = "allow *"
        caps osd = "allow *"


8月 27 22:30:44 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:30:44.308+0800 7f6978a68700 -1 mgr.server reply reply (22) Invalid argument No handler found for 'fs subvolume metadata set'
8月 27 22:35:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:35:00.376+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:35:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:35:00.376+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:35:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:35:00.376+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:35:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:35:00.376+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:35:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:35:00.376+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:35:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:35:00.497+0800 7f6978a68700 -1 mgr.server reply reply (22) Invalid argument No handler found for 'fs subvolume metadata set'
8月 27 22:40:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:40:00.553+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:40:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:40:00.553+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:40:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:40:00.553+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:40:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:40:00.553+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:40:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:40:00.553+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:40:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:40:00.646+0800 7f6978a68700 -1 mgr.server reply reply (22) Invalid argument No handler found for 'fs subvolume metadata set'
8月 27 22:41:02 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:41:02.648+0800 7f6978a68700 -1 mgr.server reply reply (22) Invalid argument No handler found for 'fs subvolume metadata set'
8月 27 22:45:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:45:00.701+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:45:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:45:00.701+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:45:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:45:00.701+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:45:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:45:00.701+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:45:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:45:00.701+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:45:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:45:00.843+0800 7f6978a68700 -1 mgr.server reply reply (22) Invalid argument No handler found for 'fs subvolume metadata set'
8月 27 22:47:08 ceph-node-1 systemd[1]: [/usr/lib/systemd/system/ceph-mgr@.service:15] Unknown lvalue 'LockPersonality' in section 'Service'
8月 27 22:47:08 ceph-node-1 systemd[1]: [/usr/lib/systemd/system/ceph-mgr@.service:18] Unknown lvalue 'MemoryDenyWriteExecute' in section 'Service'
8月 27 22:47:08 ceph-node-1 systemd[1]: [/usr/lib/systemd/system/ceph-mgr@.service:21] Unknown lvalue 'ProtectControlGroups' in section 'Service'
8月 27 22:47:08 ceph-node-1 systemd[1]: [/usr/lib/systemd/system/ceph-mgr@.service:23] Unknown lvalue 'ProtectKernelModules' in section 'Service'
8月 27 22:47:08 ceph-node-1 systemd[1]: [/usr/lib/systemd/system/ceph-mgr@.service:24] Unknown lvalue 'ProtectKernelTunables' in section 'Service'
8月 27 22:50:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:50:00.924+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:50:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:50:00.924+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:50:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:50:00.924+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:50:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:50:00.924+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:50:00 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:50:00.924+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:50:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:50:01.017+0800 7f6978a68700 -1 mgr.server reply reply (22) Invalid argument No handler found for 'fs subvolume metadata set'
8月 27 22:55:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:55:01.081+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:55:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:55:01.081+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:55:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:55:01.081+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:55:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:55:01.082+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:55:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:55:01.082+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 22:55:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:55:01.162+0800 7f6978a68700 -1 mgr.server reply reply (22) Invalid argument No handler found for 'fs subvolume metadata set'
8月 27 22:56:02 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T22:56:02.694+0800 7f6978a68700 -1 mgr.server reply reply (22) Invalid argument No handler found for 'fs subvolume metadata set'
8月 27 23:00:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T23:00:01.227+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 23:00:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T23:00:01.227+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 23:00:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T23:00:01.227+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 23:00:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T23:00:01.227+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 23:00:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T23:00:01.227+0800 7f6979269700 -1 client.0 error registering admin socket command: (17) File exists
8月 27 23:00:01 ceph-node-1 ceph-mgr[1974609]: 2022-08-27T23:00:01.526+0800 7f6978a68700 -1 mgr.server reply reply (22) Invalid argument No handler found for 'fs subvolume metadata set'
```
