### ISSUE TITLE
ceph-csi-rbd configmap rbac broken

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#342]
We have had breakage after we moved to the newest chart. We tracked down the issue to this commit:
5c600a1bc5193b35c1f050fda527bd83be6d04c7

This fixed a bug where too many permissions were given to the provisioner but exposed a bug where the driver was always writing configmaps to the default namespace, not the configured namespace and after that commit, the provisioner no longer has permissions to write to all namespaces.

So, we need to come up with a migration plan to fix this...

**Comment by kfox1111** [comment]
@plnordquist @rootfs

**Comment by bennycooly** [comment]
I'm having this same issue when using the ceph-csi-rbd chart (v1.0.0). Until this is fixed, I'm using a temporary solution for granting the provisioner service account permissions:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ceph-csi-rbd-provisioner
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-csi-rbd-provisioner
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-csi-rbd-provisioner
subjects:
- kind: ServiceAccount
  name: ceph-csi-rbd-provisioner
  namespace: ceph-csi-rbd
```
