### ISSUE TITLE
Inaccuracy in the documentation

### ISSUE THREAD

**Issue by kkrasnov1** [ceph/ceph-csi#3714]
# Describe the bug #
Documentation section [Resize RBD image](https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md#resize-rbd-image) contain 
`Once the rbd image is resized in the ceph cluster, update the PV size and PVC size to match the size of the rbd image.`
For static volumes, there is no option to change **pvc.spec.resources.requests.storage**. 

An error is thrown when trying to expand **pvc.spec.resources.requests.storage**:
`error: persistentvolumeclaims "default-pgdata-1" could not be patched: persistentvolumeclaims "default-pgdata-1" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize`

**Comment by Madhu-1** [comment]
@kkrasnov1 please check you have patched the PV first and then PVC. please specify the steps you followed so that someone can verify it.

**Comment by kkrasnov1** [comment]
Step to reproduce:

1. Create RBD volume:
```
rbd image 'test-pv01':
        size 10 GiB in 2560 objects
        order 22 (4 MiB objects)
        snapshot_count: 0
        id: 2b008ace314fc
        block_name_prefix: rbd_data.2b008ace314fc
        format: 2
        features: layering
        op_features:
        flags:
        create_timestamp: Mon Mar 13 11:27:12 2023
        access_timestamp: Mon Mar 13 11:27:12 2023
        modify_timestamp: Mon Mar 13 11:27:12 2023
```
2. Create PV and PVC
```bash
cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv01
  labels:
    application: test-ceph-csi
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: rbd.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-rbd-secret-kubeldc
      # node stage secret namespace where above secret is created
      namespace: default
      
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "XXXXXXX"
      "pool": "hddpool"
      "staticVolume": "true"
      "imageFeatures": "layering"
      #mounter: rbd-nbd
    # volumeHandle should be same as rbd image name
    volumeHandle: test-pv01
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
EOF


cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc01
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      application: test-ceph-csi
EOF
```
3. Check PV and PVC
```
$ k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                           STORAGECLASS      REASON   AGE
test-pv01                                  10Gi       RWO            Retain           Available                                                              29s

$ k get pvc
NAME         STATUS   VOLUME      CAPACITY   ACCESS MODES   STORAGECLASS   AGE
test-pvc01   Bound    test-pv01   10Gi       RWO                           12s
```

4. Expand RBD

```
rbd image 'test-pv01':
        size 12 GiB in 3072 objects
        order 22 (4 MiB objects)
        snapshot_count: 0
        id: 2b008ace314fc
        block_name_prefix: rbd_data.2b008ace314fc
        format: 2
        features: layering
        op_features:
        flags:
        create_timestamp: Mon Mar 13 11:27:12 2023
        access_timestamp: Mon Mar 13 11:27:12 2023
        modify_timestamp: Mon Mar 13 11:27:12 2023
```

5. Set pv.spec.capacity.storage: 12Gi

```
$ k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                           STORAGECLASS      REASON   AGE
test-pv01                                  12Gi       RWO            Retain           Bound       trident/test-pvc01                                         8m56s
```

6. Set pvc.spec.resources.requests.storage: 12Gi
```
error: persistentvolumeclaims "test-pvc01" could not be patched: persistentvolumeclaims "test-pvc01" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
```
