### ISSUE TITLE
deploy: more than one affinity in provisioner deployment when deploy helm chart with value provisioner.affinity

### ISSUE THREAD

**Issue by dashjay** [ceph/ceph-csi#3750]
# Describe the bug #

When I try to deploy the ceph-csi-rbd chart with value `provisioner.affinity`, there will be two affinities field in deployment provisioner.

# Environment details #

- Helm chart version : devel
- Kernel version : 5.4.0-1105
- Kubernetes cluster version : 1.12.22

# Steps to reproduce #

It's ok, when I deploy with default values.yaml 
```
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ceph-csi-rbd
                  - key: component
                    operator: In
                    values:
                      - provisioner
              topologyKey: "kubernetes.io/hostname"
```

Then I deploy with a custom-values.yaml like this:

```
provisioner:
  affinity:
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - test-0001.com
            - test-0002.com
            - test-0003.com
```
There will be two affinity in rendered yaml, if this was applied into kubernetes, the inferior affinity will take effect, superior affinity will be lost, This should not be a correct thing.

# Actual results #

Yaml renderer out like this:
```
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
....
      affinity:
        nodeAffinity:
....
```

# Expected behavior #

Yaml should be renderer out like this:
```
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
        nodeAffinity:
```
