### ISSUE TITLE
VolumeResizeFailed Warning events when resizing CephFS volume mounted by multiple pods

### ISSUE THREAD

**Issue by simu** [ceph/ceph-csi#3929]
# Describe the bug #

Online resizing of CephFS volumes mounted by multiple pods on multiple nodes generates `Warning` events like the following:

```
58m         Warning   VolumeResizeFailed       pod/shell-d8cc6586-xzvk2                   NodeExpandVolume.NodeExpandVolume failed for volume "pvc-0a108d5a-94e1-4abd-b321-0c3e18efc506" : Expander.NodeExpand found CSI plugin kubernetes.io/csi/syn-rook-ceph-operator.cephfs.csi.ceph.com to not support node expansion
```

Despite those warnings the volume is resized correctly as far as I'm able to tell.

# Environment details #

- Image/version of Ceph CSI driver : quay.io/cephcsi/cephcsi:v3.8.0
- Helm chart version : Installed through Rook 1.11.8
- Kernel version : `4.18.0-372.58.1.el8_6.x86_64`
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : `kernel`
- Kubernetes cluster version : OpenShift 4.11.42 / Kubernetes `v1.24.12+ceaf338`
- Ceph cluster version : `ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)`

# Steps to reproduce #

## Rook configuration ##

Rook operator ConfigMap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
data:
  CSI_CEPHFS_ATTACH_REQUIRED: "true"
  CSI_CEPHFS_FSGROUPPOLICY: File
  CSI_CEPHFS_PLUGIN_RESOURCE: |
    - name : driver-registrar
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 100m
    - name : csi-cephfsplugin
      resource:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 1Gi
          cpu: 500m
    - name : liveness-prometheus
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 100m
  CSI_CEPHFS_PROVISIONER_RESOURCE: |
    - name : csi-provisioner
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-resizer
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-attacher
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-snapshotter
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-cephfsplugin
      resource:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 1Gi
          cpu: 500m
    - name : liveness-prometheus
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 100m
  CSI_ENABLE_CEPHFS_SNAPSHOTTER: "true"
  CSI_ENABLE_CSIADDONS: "false"
  CSI_ENABLE_ENCRYPTION: "false"
  CSI_ENABLE_HOST_NETWORK: "false"
  CSI_ENABLE_LIVENESS: "true"
  CSI_ENABLE_METADATA: "false"
  CSI_ENABLE_NFS_SNAPSHOTTER: "true"
  CSI_ENABLE_OMAP_GENERATOR: "false"
  CSI_ENABLE_RBD_SNAPSHOTTER: "true"
  CSI_ENABLE_READ_AFFINITY: "false"
  CSI_ENABLE_TOPOLOGY: "false"
  CSI_FORCE_CEPHFS_KERNEL_CLIENT: "true"
  CSI_GRPC_TIMEOUT_SECONDS: "150"
  CSI_NFS_ATTACH_REQUIRED: "true"
  CSI_NFS_FSGROUPPOLICY: File
  CSI_NFS_PLUGIN_RESOURCE: |
    - name : driver-registrar
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
    - name : csi-nfsplugin
      resource:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
  CSI_NFS_PROVISIONER_RESOURCE: |
    - name : csi-provisioner
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-nfsplugin
      resource:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
    - name : csi-attacher
      resource:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
  CSI_PLUGIN_ENABLE_SELINUX_HOST_MOUNT: "false"
  CSI_PLUGIN_PRIORITY_CLASSNAME: system-node-critical
  CSI_PROVISIONER_PRIORITY_CLASSNAME: system-cluster-critical
  CSI_PROVISIONER_REPLICAS: "2"
  CSI_PROVISIONER_TOLERATIONS: |-
    - key: storagenode
      operator: Exists
  CSI_RBD_ATTACH_REQUIRED: "true"
  CSI_RBD_FSGROUPPOLICY: File
  CSI_RBD_PLUGIN_RESOURCE: |
    - name : driver-registrar
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 100m
    - name : csi-rbdplugin
      resource:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 1Gi
          cpu: 500m
    - name : liveness-prometheus
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 100m
  CSI_RBD_PROVISIONER_RESOURCE: |
    - name : csi-provisioner
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-resizer
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-attacher
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-snapshotter
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-rbdplugin
      resource:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 1Gi
          cpu: 500m
    - name : csi-omap-generator
      resource:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 1Gi
          cpu: 500m
    - name : liveness-prometheus
      resource:
        requests:
          memory: 32Mi
          cpu: 10m
        limits:
          memory: 256Mi
          cpu: 100m
  ROOK_CEPH_ALLOW_LOOP_DEVICES: "false"
  ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS: "15"
  ROOK_CSI_CEPH_IMAGE: quay.io/cephcsi/cephcsi:v3.8.0
  ROOK_CSI_ENABLE_CEPHFS: "true"
  ROOK_CSI_ENABLE_GRPC_METRICS: "true"
  ROOK_CSI_ENABLE_NFS: "false"
  ROOK_CSI_ENABLE_RBD: "true"
  ROOK_CSI_IMAGE_PULL_POLICY: IfNotPresent
  ROOK_CSIADDONS_IMAGE: quay.io/csiaddons/k8s-sidecar:v0.5.0
  ROOK_DISABLE_ADMISSION_CONTROLLER: "true"
  ROOK_LOG_LEVEL: INFO
  ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true"
```

Rook CephCluster resource

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  labels:
    app.kubernetes.io/component: rook-ceph
    app.kubernetes.io/managed-by: commodore
    app.kubernetes.io/name: cluster
    argocd.argoproj.io/instance: rook-ceph
    name: cluster
  name: cluster
spec:
  cephVersion:
    allowUnsupported: false
    image: quay.io/ceph/ceph:v17.2.6
  cleanupPolicy:
    sanitizeDisks: {}
  crashCollector: {}
  dashboard: {}
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  external: {}
  healthCheck:
    daemonHealth:
      mon: {}
      osd: {}
      status: {}
  logCollector: {}
  mgr: {}
  mon:
    allowMultiplePerNode: false
    count: 3
  monitoring:
    enabled: true
  network:
    provider: host
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/storage
              operator: Exists
      tolerations:
      - key: storagenode
        operator: Exists
  resources:
    mgr:
      limits:
        memory: 750Mi
      requests:
        cpu: 50m
        memory: 750Mi
    mon:
      limits:
        memory: 1500Mi
      requests:
        cpu: 50m
        memory: 1500Mi
    osd:
      limits:
        memory: 1500Mi
      requests:
        cpu: 50m
        memory: 1500Mi
  security:
    kms: {}
  storage:
    storageClassDeviceSets:
    - count: 3
      encrypted: true
      name: cluster
      placement:
        topologySpreadConstraints:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-osd
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      portable: true
      tuneFastDeviceClass: true
      volumeClaimTemplates:
      - spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: ssd
          volumeMode: Block
    useAllDevices: false
    useAllNodes: false
status:
  ceph:
    capacity:
      bytesAvailable: 311252185088
      bytesTotal: 322072215552
      bytesUsed: 10820030464
      lastUpdated: "2023-06-22T11:49:25Z"
    fsid: 90929098-cd30-46cb-8080-7010e50d21a0
    health: HEALTH_OK
    lastChanged: "2023-06-22T09:41:33Z"
    lastChecked: "2023-06-22T11:49:25Z"
    previousHealth: HEALTH_WARN
    versions:
      mds:
        ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable): 2
      mgr:
        ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable): 1
      mon:
        ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable): 3
      osd:
        ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable): 3
      overall:
        ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable): 9
  conditions:
  - lastHeartbeatTime: "2023-06-22T11:49:25Z"
    lastTransitionTime: "2023-01-12T07:54:55Z"
    message: Cluster created successfully
    reason: ClusterCreated
    status: "True"
    type: Ready
  message: Cluster created successfully
  observedGeneration: 14
  phase: Ready
  state: Created
  storage:
    deviceClasses:
    - name: hdd
  version:
    image: quay.io/ceph/ceph:v17.2.6
    version: 17.2.6-0
```

## Deployment

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
spec:
  replicas: 4
  selector:
    matchLabels:
      name: shell
  template:
    metadata:
      labels:
        name: shell
    spec:
      tolerations:
        - key: "node.kubernetes.io/unschedulable"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - shell
              topologyKey: kubernetes.io/hostname
      serviceAccountName: shell
      containers:
        - name: shell
          image: dockerhub.vshn.net/library/ubuntu:latest
          command: ['/bin/sh', '-c', 'trap : TERM INT; sleep infinity & wait']
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
          volumeMounts:
            - name: data
              mountPath: /data
      dnsPolicy: ClusterFirst
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: test-vol
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: cephfs-fspool-cluster
```

Run the following command after all shell pods are running:

```
kubectl patch pvc test-vol -p '{"spec":{"resources":{"requests":{"storage":"10Gi"}}}}'
```

Wait a moment, then you'll start observing Warning events like the following:

```
58m         Warning   VolumeResizeFailed       pod/shell-d8cc6586-xzvk2                   NodeExpandVolume.NodeExpandVolume failed for volume "pvc-0a108d5a-94e1-4abd-b321-0c3e18efc506" : Expander.NodeExpand found CSI plugin kubernetes.io/csi/syn-rook-ceph-operator.cephfs.csi.ceph.com to not support node expansion
```

# Actual results #

Warning events like the following are emitted in regular intervals until (as far as I was able to determine), all pods are either stopped completely and restarted (with `kubectl scale deploy/shell --replicas=0`, waiting until no pods running and scaling up again), or all pods are scheduled on nodes on which the volume wasn't mounted before the resize.

# Expected behavior #

No warning events are emitted for a resize which otherwise seems successful (all pods see the new volume size) 

# Logs #

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

## csi-cephfsplugin

```
$ kubectl -n syn-rook-ceph-operator logs csi-cephfsplugin-provisioner-fd97946b6-bcwjt csi-cephfsplugin 
E0622 10:56:52.755444       1 cephcsi.go:221] Failed to set new PID limit to -1: open /sys/fs/cgroup/pids/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pode5baf250_d70e_4ff2_a5af_4669be3a5dad.slice/crio-bbadde89769a07a70802de63865de6a061400a0e0949af8937553a6dd7501436.scope/pids.max: permission denied
W0622 10:56:52.779812       1 driver.go:160] EnableGRPCMetrics is deprecated
$ kubectl -n syn-rook-ceph-operator logs csi-cephfsplugin-provisioner-fd97946b6-c99cl csi-cephfsplugin 
E0622 10:57:06.356097       1 cephcsi.go:221] Failed to set new PID limit to -1: open /sys/fs/cgroup/pids/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod87c98a2f_4b56_4c4a_97fb_0869b89210f6.slice/crio-ceeb8e58f77d79e5352f5ec66e93a834bf95eb45b2efc4230fca9761786f2990.scope/pids.max: permission denied
W0622 10:57:06.390622       1 driver.go:160] EnableGRPCMetrics is deprecated
```

## csi-resizer

```
$ kubectl -n syn-rook-ceph-operator logs csi-cephfsplugin-provisioner-fd97946b6-c99cl csi-resizer 
I0622 10:56:52.627766       1 main.go:93] Version : v1.7.0
W0622 10:57:02.630423       1 connection.go:173] Still connecting to unix:///csi/csi-provisioner.sock
I0622 10:57:06.580510       1 common.go:111] Probing CSI driver for readiness
I0622 10:57:06.591256       1 leaderelection.go:248] attempting to acquire leader lease syn-rook-ceph-operator/external-resizer-syn-rook-ceph-operator-cephfs-csi-ceph-com...
$ kubectl -n syn-rook-ceph-operator logs csi-cephfsplugin-provisioner-fd97946b6-bcwjt csi-resizer 
I0622 10:56:52.253032       1 main.go:93] Version : v1.7.0
I0622 10:56:53.259367       1 common.go:111] Probing CSI driver for readiness
I0622 10:56:53.263558       1 leaderelection.go:248] attempting to acquire leader lease syn-rook-ceph-operator/external-resizer-syn-rook-ceph-operator-cephfs-csi-ceph-com...
I0622 10:59:20.252840       1 leaderelection.go:258] successfully acquired lease syn-rook-ceph-operator/external-resizer-syn-rook-ceph-operator-cephfs-csi-ceph-com
I0622 10:59:20.253583       1 controller.go:255] Starting external resizer syn-rook-ceph-operator.cephfs.csi.ceph.com
I0622 11:07:27.144222       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"sg-test", Name:"test-vol", UID:"0a108d5a-94e1-4abd-b321-0c3e18efc506", APIVersion:"v1", ResourceVersion:"709245534", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-0a108d5a-94e1-4abd-b321-0c3e18efc506
I0622 11:07:27.262979       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"sg-test", Name:"test-vol", UID:"0a108d5a-94e1-4abd-b321-0c3e18efc506", APIVersion:"v1", ResourceVersion:"709245534", FieldPath:""}): type: 'Normal' reason: 'VolumeResizeSuccessful' Resize volume succeeded
```

Excerpt from one worker node on which the volume to resize was mounted:

```
[Thu Jun 22 07:17:24 2023] libceph: mon0 (1)172.18.200.146:6789 session established
[Thu Jun 22 07:17:24 2023] libceph: client24180240 fsid 90929098-cd30-46cb-8080-7010e50d21a0
[Thu Jun 22 07:17:24 2023] ceph: mds0 session blocklisted
[Thu Jun 22 07:17:24 2023] IPv6: ADDRCONF(NETDEV_UP): lxc67f776e85cb1: link is not ready
[Thu Jun 22 07:17:24 2023] eth0: renamed from tmpde110
[Thu Jun 22 07:17:24 2023] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[Thu Jun 22 07:17:24 2023] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[Thu Jun 22 07:17:24 2023] IPv6: ADDRCONF(NETDEV_CHANGE): lxc67f776e85cb1: link becomes ready
[Thu Jun 22 09:46:08 2023] libceph: mon2 (1)172.18.200.132:6789 session established
[Thu Jun 22 09:46:08 2023] libceph: client24214849 fsid 90929098-cd30-46cb-8080-7010e50d21a0
[Thu Jun 22 09:46:08 2023] ceph: mds0 session blocklisted
[Thu Jun 22 09:46:08 2023] IPv6: ADDRCONF(NETDEV_UP): lxc8fb56c341f55: link is not ready
[Thu Jun 22 09:46:08 2023] eth0: renamed from tmp8fb21
[Thu Jun 22 09:46:08 2023] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[Thu Jun 22 09:46:08 2023] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[Thu Jun 22 09:46:08 2023] IPv6: ADDRCONF(NETDEV_CHANGE): lxc8fb56c341f55: link becomes ready
[Thu Jun 22 10:44:32 2023] libceph: mon2 (1)172.18.200.132:6789 session established
[Thu Jun 22 10:44:32 2023] libceph: client24215920 fsid 90929098-cd30-46cb-8080-7010e50d21a0
[Thu Jun 22 10:44:32 2023] ceph: mds0 session blocklisted
[Thu Jun 22 10:44:32 2023] IPv6: ADDRCONF(NETDEV_UP): lxc044150d59457: link is not ready
[Thu Jun 22 10:44:32 2023] eth0: renamed from tmp3da97
[Thu Jun 22 10:44:32 2023] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[Thu Jun 22 10:44:32 2023] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[Thu Jun 22 10:44:32 2023] IPv6: ADDRCONF(NETDEV_CHANGE): lxc044150d59457: link becomes ready
[Thu Jun 22 10:57:00 2023] IPv6: ADDRCONF(NETDEV_UP): lxc2ea4d0f3f139: link is not ready
[Thu Jun 22 10:57:00 2023] eth0: renamed from tmpb5f47
[Thu Jun 22 10:57:00 2023] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[Thu Jun 22 10:57:00 2023] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[Thu Jun 22 10:57:00 2023] IPv6: ADDRCONF(NETDEV_CHANGE): lxc2ea4d0f3f139: link becomes ready
[Thu Jun 22 10:57:34 2023] IPv6: ADDRCONF(NETDEV_UP): lxc896c42894299: link is not ready
[Thu Jun 22 10:57:34 2023] eth0: renamed from tmp7469c
[Thu Jun 22 10:57:34 2023] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[Thu Jun 22 10:57:34 2023] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[Thu Jun 22 10:57:34 2023] IPv6: ADDRCONF(NETDEV_CHANGE): lxc896c42894299: link becomes ready
[Thu Jun 22 11:07:13 2023] libceph: mon1 (1)172.18.200.132:6789 session established
[Thu Jun 22 11:07:13 2023] libceph: client24216343 fsid 90929098-cd30-46cb-8080-7010e50d21a0
[Thu Jun 22 11:07:13 2023] ceph: mds0 session blocklisted
[Thu Jun 22 11:07:13 2023] IPv6: ADDRCONF(NETDEV_UP): lxcfd0816293597: link is not ready
[Thu Jun 22 11:07:13 2023] eth0: renamed from tmpf014a
[Thu Jun 22 11:07:13 2023] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[Thu Jun 22 11:07:13 2023] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[Thu Jun 22 11:07:13 2023] IPv6: ADDRCONF(NETDEV_CHANGE): lxcfd0816293597: link becomes ready
```

# Additional context #

May be a similar issue as reported in https://github.com/rook/rook/issues/11344, but the volume I'm testing with has exactly one large file (created with `dd if=/dev/zero of=/data/tmp.dat bs=1M count=3072`)
