### ISSUE TITLE
Creating volume snapshots using different CEPH clusters

### ISSUE THREAD

**Issue by am6737** [ceph/ceph-csi#4028]
# Describe the feature you'd like to have #

I have two ceph clusters here, ceph1 and ceph2. I created sc1 based on ceph1 and used sc1 to create test PVC. I created a VolumeSnapshotClass named csi rbdplugin snapclass based on ceph2, and I want to use the snapshot class csi rbdplugin snapclass to create snapshots based on test PVC.

Overall, what I want is for the created PVC to be stored in ceph1 and the created snapshot to be stored in ceph2

I want to know if I can do this or how I can do it

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snap-test-pvc
spec:
  volumeSnapshotClassName: csi-rbdplugin-snapclass
  source:
    persistentVolumeClaimName: test-pvc
```

VolumeSnapshotContent error message
```
Failed to check and update snapshot content: failed to take snapshot of the volume 0001-0024-89bc6b66-eaea-11ed-ad7d-e138c36c1e52-0000000000000002-05d8e03d-db02-4b44-afa9-cd5500b18b06: "rpc error: code = Internal desc = failed to establish the connection: failed to get connection: connecting failed: rados: ret=-13, Permission denied"
```

# What is the value to the end user? (why is it a priority?) #

How would the end user gain value from having this feature?

# How will we know we have a good solution? (acceptance criteria) #

Add a list of criteria that should be met for this feature to be useful

# Additional context #
