### ISSUE TITLE
How to create a pre-provisioned PV for an existing rbd image

### ISSUE THREAD

**Issue by itmuckel** [ceph/ceph-csi#407]
In https://kubernetes.io/blog/2019/01/15/container-storage-interface-ga/ under the section "Pre-Provisioned Volumes" is a template of how to create a PV from a prepopulated CSI volume. What values do I need to create a PV that references an rbd image? Once the PV is created, I'm sure just creating a PVC will bind automatically to the PV.

I've read a lot of the official kubernetes docs, but how do I get the csi driver, volume handle, fsType? What volumeAttributes do I need? What secrets do I need to reference.

I've set up ceph-csi using rook following the following documentation: https://rook.io/docs/rook/v1.0/ceph-csi-drivers.html

**Comment by ShyamsundarR** [comment]
I did a round of tests with pre-provisioned CephFS volumes (or directories) and exposing them as static PVs or pre-provisioned volumes, the requires YAML for that test/example can be found [here](https://gist.github.com/ShyamsundarR/1009b79966992470f588a277429ae2e1). This maybe a little dated, but can serve as an example for RBD as well.

Let me know if this helps, else I can create one for RBD as well and post it.

**Comment by itmuckel** [comment]
@ShyamsundarR Yes, please show me how a file for rbd restoration should look.

My current file looks like this:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: verdaccio-restored-from-rbd
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  csi:
    driver: rbd.csi.ceph.com
    volumeHandle: verdaccio-pvc-backup
    readOnly: false
    fsType: ext4
    nodeStageSecretRef:
      name: csi-rbd-secret
      namespace: csi
    controllerPublishSecretRef:
      name: csi-rbd-secret
      namespace: csi
    nodePublishSecretRef:
      name: csi-rbd-secret
      namespace: csi
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: verdaccio-test-backup
    name: verdaccio-restored-from-rbd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: verdaccio-test-backup
  name: verdaccio-restored-from-rbd
spec:
  storageClassName: csi-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```

The only value that ties this pv to the rbd is the `volumeHandle`. It is the same name as the rbd.
When I try to use this, I get the following error at pod level:

```
Events:
  Type     Reason                  Age                   From                              Message
  ----     ------                  ----                  ----                              -------
  Normal   Scheduled               6m9s                  default-scheduler                 Successfully assigned verdaccio-test-backup/verdaccio-7884b5db74-thjwv to <<my-node>>
  Normal   SuccessfulAttachVolume  6m7s                  attachdetach-controller           AttachVolume.Attach succeeded for volume "verdaccio-restored-from-rbd"
  Warning  FailedMount             103s (x2 over 4m1s)   kubelet, <<my-node>>            Unable to mount volumes for pod "verdaccio-7884b5db74-thjwv_verdaccio-test-backup(dc458210-9811-11e9-a97c-d4ae52ad4f13)": timeout expired waiting for volumes to attach or mount for pod "verdaccio-test-backup"/"verdaccio-7884b5db74-thjwv". list of unmounted volumes=[storage]. list of unattached volumes=[storage default-token-5fsnp]
  Warning  FailedMount             77s (x10 over 5m46s)  kubelet, <<my-node>>           MountVolume.SetUp failed for volume "verdaccio-restored-from-rbd" : rpc error: code = Unknown desc = missing required parameter pool
```

My pool is called `rbd`, just the default name, but where in the PersistentVolume definition can I specify it. Also, is my assumption that `volumeHandle == rbd-name` right?

Thanks for your help, I appreciate it a lot!

**Comment by reith** [comment]
@ShyamsundarR Is static PV for block volumes are supported too? My PV's being created but I doubt it even talked with RBD, since I see same behavior with having and not having `rootPath`.

My RBD image is `t1` in `pool`:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reithpvtest
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  csi:
    driver: rbd.csi.ceph.com
    nodePublishSecretRef:
      name: rbdsecret
      namespace: rbd
    volumeAttributes:
      preProvisionedVolume: "true"
      adminid: admin
      imageFeatures: layering
      imageFormat: "2"
      monitors: 172.17.8.48:6789,172.17.8.49:6789,172.17.8.50:6789
      pool: pool
      userid: admin
      rootPath: t1
      reclaimPolicy: Retain
    volumeHandle: t1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-csi-volumes
  volumeMode: Block
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: reithpvtest
spec:
  storageClassName: ceph-csi-volumes
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: reithpvtest
  volumeMode: Block
---
apiVersion: v1
kind: Pod
metadata:
  name: reithpvtest
spec:
  containers:
    - name: my-container
      image: busybox
      command:
        - sleep
        - "3600"
      volumeDevices:
        - devicePath: /dev/block
          name: reithpvtest
      imagePullPolicy: IfNotPresent
  volumes:
    - name: reithpvtest
      persistentVolumeClaim:
        claimName: reithpvtest
```

PV bounds (which I assume is just a check for accessModes and size…) but mount fails:
```
  Warning  FailedMount         <invalid> (x2 over <invalid>)  kubelet, node0206.compute.east  Unable to mount volumes for pod "reithpvtest_default(22e8ceb0-b751-11e9-a6e4-1402ec05bdd4)": timeout expired waiting for volumes to attach or mount for pod "default"/"reithpvtest". list of unmounted volumes=[reithpvtest]. list of unattached volumes=[reithpvtest default-token-q8hvv]
  Warning  FailedAttachVolume  <invalid> (x9 over 105s)       attachdetach-controller         AttachVolume.Attach failed for volume "reithpvtest" : attachment timeout for volume t1
```
