### ISSUE TITLE
Persistent Volume - cannot write file content but can create directories and empty files

### ISSUE THREAD

**Issue by radoen** [ceph/ceph-csi#4351]
# Describe the bug #

I used this guide https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md#create-cephfs-static-pv to set up a static PV and relative claims with 

  - ceph fs subvolumegroup create xxxx-shared-fs atomicsGroup
  - ceph fs subvolume create  xxxx-shared-fs  atomicsRepository atomicsGroup --size=50073741824

then I created PV and PVC as following 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: atomic-cloner-volume
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: rook-ceph
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "rook-ceph"
      "fsName": " xxxx-shared-fs"
      "staticVolume": "true"
      "rootPath": /volumes/atomicsGroup/atomicsRepository/51cc4962-c416-45a3-9791-c134546af60a
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: atomic-cloner-volume
  persistentVolumeReclaimPolicy: Retain

```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atomic-cloner-volume-claim
  namespace: shared-services
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  # volumeName should be same as PV name
  volumeName: atomic-cloner-volume
```

last step is to attach the volume to a pod.
claim bounded and inside the POD I'm able to create file with **touch** and to create subfolders with **mkdir** in the volume, but I got permission deny if I try to write something inside a file or to copy and existent one. delete on file and directory works.

am I missing something or it's a bug?

# Environment details #

- Kernel version : 6.1.0-12-amd64
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : fuse
- Kubernetes cluster version : Kubernetes 1.28.2-do.0
- Ceph cluster version : ceph version 18.2.0 (5dd24139a1eada541a3bc16b6941c5dde975e26d) reef (stable)

# Expected behavior #

to be able to write also content in files.
