### ISSUE TITLE
Pods are in CrashLoopBackOff state in Hygon CPU environment.

### ISSUE THREAD

**Issue by Goend** [ceph/ceph-csi#4379]
# Describe the bug #
Pods always are in CrashLoopBackOff.some logs in dmesg.
However, this container image was built by me,
The community image is available in the environment.
I got it by 
```
make image-cephcsi
```
Later, I built it in GitHub Actions to avoid the difference with localhost.
```
---
name: multi-arch-build
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
permissions:
  contents: read

jobs:
  codespell:
    name: multi-arch-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: multi-arch-build
        # yamllint disable-line rule:line-length
        if: ${{ ! contains(github.event.pull_request.labels.*.name, 'ci/skip/multi-arch-build') }}
        # podman cannot pull images with both tag and digest
        # https://github.com/containers/buildah/issues/1407
        # use docker to build images
        run: CONTAINER_CMD=docker ./scripts/build-multi-arch-image.sh
      - name: single-arch-build
        # yamllint disable-line rule:line-length
        if: ${{ contains(github.event.pull_request.labels.*.name, 'ci/skip/multi-arch-build') }}
        run: make containerized-build
      - name: Build binary
        run: |
          echo "creating images cache..."
          docker save hub.easystack.io/captain/cephcsi:v3.9.0-es| pigz > ceph-csi-x86.tar.gz
          docker save hub.easystack.io/arm64v8/cephcsi:v3.9.0-es| pigz > ceph-csi-arm.tar.gz
      - name: cache x86 image
        uses: actions/upload-artifact@v2
        with:
          name: ceph-csi-x86.tar.gz
          path: ceph-csi-x86.tar.gz
      - name: cache arm image
        uses: actions/upload-artifact@v2
        with:
          name: ceph-csi-arm.tar.gz
          path: ceph-csi-arm.tar.gz
```

# Environment details #
```
[root@node-6 ~]# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  2
Core(s) per socket:  32
Socket(s):           2
NUMA node(s):        8
Vendor ID:           HygonGenuine
BIOS Vendor ID:      Chengdu Hygon
CPU family:          24
Model:               2
Model name:          Hygon C86 7380 32-core Processor
BIOS Model name:     Hygon C86 7380 32-core Processor
Stepping:            2
CPU MHz:             2471.242
BogoMIPS:            4400.19
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           64K
L2 cache:            512K
L3 cache:            8192K
NUMA node0 CPU(s):   0-7,64-71
NUMA node1 CPU(s):   8-15,72-79
NUMA node2 CPU(s):   16-23,80-87
NUMA node3 CPU(s):   24-31,88-95
NUMA node4 CPU(s):   32-39,96-103
NUMA node5 CPU(s):   40-47,104-111
NUMA node6 CPU(s):   48-55,112-119
NUMA node7 CPU(s):   56-63,120-127
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sme sev sev_es
```

- Image/version of Ceph CSI driver :
v3.9.0
- Helm chart version :
- Kernel version :
```
[root@node-6 ~]# uname -a
Linux node-6.domain.tld 4.18.0-372.19.1.es8_8.x86_64 #1 SMP Tue Jan 2 14:54:00 CST 2024 x86_64 x86_64 x86_64 GNU/Linux
```
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version :
- Ceph cluster version :

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened

# Expected behavior #

# Logs #

```
Jan 15 20:34:36 node-5 kernel: cephcsi[20662]: segfault at 53666c0 ip 00007fa9381ecf20 sp 00007ffd196ea348 error 6 in libc-2.28.so[7fa9381c8000+1cd000]
Jan 15 20:34:52 node-5 kernel: cephcsi[20944]: segfault at 51af6c0 ip 00007f59a1728f20 sp 00007ffe99f6f968 error 6 in libc-2.28.so[7f59a1704000+1cd000]
Jan 15 20:35:18 node-5 kernel: cephcsi[21692]: segfault at 4e3f6c0 ip 00007efdb7fb3f20 sp 00007ffcd3b7e238 error 6 in libc-2.28.so[7efdb7f8f000+1cd000]
Jan 15 20:35:41 node-5 kernel: cephcsi[22239]: segfault at 39eb6c0 ip 00007fd8aef9af20 sp 00007ffe82e6e318 error 6 in libc-2.28.so[7fd8aef76000+1cd000]
Jan 15 20:35:42 node-5 kernel: cephcsi[22312]: segfault at 396c6c0 ip 00007f57c3e19f20 sp 00007ffc924a85e8 error 6 in libc-2.28.so[7f57c3df5000+1cd000]
Jan 15 20:35:55 node-5 kernel: cephcsi[22546]: segfault at 43226c0 ip 00007f973fcbef20 sp 00007ffcb73629a8 error 6 in libc-2.28.so[7f973fc9a000+1cd000]
Jan 15 20:36:21 node-5 kernel: cephcsi[22882]: segfault at 43ed6c0 ip 00007f9bc1f1ff20 sp 00007ffee4e8f888 error 6 in libc-2.28.so[7f9bc1efb000+1cd000]
Jan 15 20:37:02 node-5 kernel: cephcsi[23357]: segfault at 403a6c0 ip 00007f0ea1487f20 sp 00007ffe2518ad78 error 6 in libc-2.28.so[7f0ea1463000+1cd000]
Jan 15 20:38:23 node-5 kernel: cephcsi[24393]: segfault at 44f86c0 ip 00007f480207df20 sp 00007ffd68f94648 error 6 in libc-2.28.so[7f4802059000+1cd000]
```
