### ISSUE TITLE
Handle multiple storage classes in Helm chart

### ISSUE THREAD

**Issue by gpothier** [ceph/ceph-csi#4484]
# Describe the feature you'd like to have #

The Helm chart currently supports the creation of one StorageClass. I think it could be useful to allow the creation of multiple storage classes, given that the chart already supports the configuration of various clusters (through the array in `csiConfig`).

Eg. instead of:
```
storageClass:
  # Specifies whether the Storage class should be created
  create: true
  name: mysc
  clusterID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  fsName: myfs
```
we could have:
```
storageClasses: {}
```
if no StorageClass should be created, or:
```
storageClasses:
  mysc:
    clusterID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    fsName: myfs
  myothersc:
    clusterID: xxxxxxxx-xxxx-xxxx-xxxx-yyyyyyyyyyyy
    fsName: myotherfs
```
(I am partial to using maps instead of arrays as it makes it easier to add different items by providing multiple values files which are then merged).

# What is the value to the end user? (why is it a priority?) #

In my particular use case, I need a storage class for volumes that contain important data that needs to be included in backups, and another one for volumes that contain temporary data, or data that does not need to be backed up. 

# How will we know we have a good solution? (acceptance criteria) #

The feature should work correctly and be clearly documented

**Comment by mustdiechik** [comment]
you can do it via extraDeploy (Secret + StorageClass )

**Comment by gpothier** [comment]
Yes, but that would be quite a lot of lines for each extra StorageClass, instead of just two lines, and we would have one SC defined in one way, and the rest defined in a completely different way.

**Comment by julienlau** [comment]
For the moment I see no solution to have the same ceph RDB backend that would provide a main storage class with different kubernetes options like bindingmode and reclaimpolicy. In addition that would also be nice to be able to have 2 different ceph clusters.
I would like to be able to easily have these storage class defined on kubernetes without having to create 1 namespace for each storageclass.

![Image](https://github.com/user-attachments/assets/2fd08cb7-647a-4544-acd2-9fc903e6ab7e)

**Comment by burnedoutman** [comment]
up!

@mustdiechik 
> you can do it via extraDeploy (Secret + StorageClass )

or please at least add to the documentation how it can be used via extraDeploy

**Comment by julienlau** [comment]
outside from the helm chart it may be supported.
I did not try it, but the config.json takes an array in input : 
`config.json: '[{"clusterID":"e-e-16-70","monitors":["b76:6789","b77:6789","b78:6789"]}]'

**Comment by burnedoutman** [comment]
> outside from the helm chart it may be supported. I did not try it, but the config.json takes an array in input : `config.json: '[{"clusterID":"e-e-16-70","monitors":["b76:6789","b77:6789","b78:6789"]}]'

thx for reply, at the moment I managed to add to the chart via extradeploy so that the linter does not complain. But so far when deploying the chart (3.10.2) (I'm trying to install 2 storage classes in one namespace, with different secret names and creds) Helm upgrade complains
"Error: Unable to continue with install: could not get information about the resource Secret "" in namespace "ceph-csi-cephfs": resource name may not be empty"
even though there is currently no ceph-csi installed in the cluster

**Comment by mustdiechik** [comment]
```
extraDeploy:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: csi-rbd-secret
      namespace: {{ .Release.Namespace }}
      annotations:
        vault.security.banzaicloud.io/vault-role: vault-role
        vault.security.banzaicloud.io/vault-serviceaccount: default
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
    data:
      userID: {{ .Values | get "ceph-csi-rbd.user" | b64enc }}
      userKey: {{ .Values | get "ceph-csi-rbd.key" | b64enc }}
      encryptionPassphrase: ""

  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: ceph2
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
    provisioner: rbd.csi.ceph.com
    parameters:
      clusterID: {{ .Values | get "ceph-csi-rbd.clusterID" }}
      pool: pool2
      imageFeatures: layering
      csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
      csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi-rbd
      csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
      csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi-rbd
      csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
      csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi-rbd
      csi.storage.k8s.io/fstype: ext4
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    mountOptions:
      - discard

```

**Comment by burnedoutman** [comment]
> ```
> extraDeploy:
>   - apiVersion: v1
> ```

thanks for the example, ~~unfortunately in this form (or in any other) it does not work in 3.10.2. Helm template (3.18.2) does not render this extraDeploy at all, without error~~

~~I tried to apply it to 3.14.0 and everything is the same~~

I used Helm template incorrectly, so far I managed to successfully deploy the secret, but for SC it says
```
I0618 13:37:54.709192      69 warnings.go:110] "Warning: unknown field \"parameters\""
I0618 13:37:54.709239      69 warnings.go:110] "Warning: unknown field \"provisioner\""
I0618 13:37:54.709245      69 warnings.go:110] "Warning: unknown field \"reclaimPolicy\""
```
and does not deploy

**Comment by burnedoutman** [comment]
swapped secret and sc and was able to deploy sc, but now it complains about an "unknown" field in secret - data or stringData (tried both options)

**Comment by burnedoutman** [comment]
ok, I was able to overcome this and deployed everything successfully. now when creating pvc in the logs of the provisioner errors
```
failed to provision volume with StorageClass "rfs-82041": rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "subvolume group 'csi' does not exist"
```
How is this possible? I have it specified in my config
```
csiConfig:
  - clusterID: "b28c3ef0-3b13-11ec-8cad-01f5553218da"
    monitors: ["%ip1%:6789","%ip2%:6789","%ip3%:6789"]
    cephFS:
      subvolumeGroup: "csi"
```
clusterID one for all sc
I need to put the same configmap into extradeployment again?
or can I specify the default subvolumegroup somewhere?
