### ISSUE TITLE
Feature Request: Automatic Directory Creation for Specified Path in PVs

### ISSUE THREAD

**Issue by christophenoel** [ceph/ceph-csi#4567]
**Description:**

Currently, when defining a PersistentVolume (PV) using the CephCSI driver, operator need to manually create the specified directory path on the CephFS file system before mounting the PV. If the directory does not exist, mounting the PV fails with an error stating that the path does not exist. 

Here is an example of a PV configuration where the path needs to be pre-created:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-pv6
spec:
  capacity:
    storage: 1Gi
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  cephfs:
    path: /volumes/default-group/test6
    user: kubernetes
    secretRef:
      name: csi-fs-secret
```

**Requested Feature**:

It would be beneficial if the CephCSI driver could support automatic creation of the specified path if it does not already exist. This feature would allow users to specify any path in the PV configuration, and the driver would ensure the path is created on the CephFS before attempting to mount the volume.

**Benefits**:

- Automation: Improves the automation capabilities by removing the need for manual pre-configuration steps.
- Flexibility: Increases flexibility in managing storage resources.

Kind regards,

Christophe
