### ISSUE TITLE
Volume provisioning with multiple ceph clusters

### ISSUE THREAD

**Issue by lechugaletal** [ceph/ceph-csi#4857]
# Volume provisioning with multiple ceph clusters #

I'm trying to find if there is a way to provision PVs from multiple ceph clusters given a StatefulSet that has a single StorageClass defined in its `volumeClaimTemplates` section.

Given a StatefulSet with a spec of `spec.volumeClaimTemplates.storageClassName: test-sc` (pointing to a single StorageClass), and a storageClass with an hypothetical spec like:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-sc
parameters:
  clusters:
    - clusterID: cluster1
      csi.storage.k8s.io/controller-expand-secret-name: cluster1
      csi.storage.k8s.io/controller-expand-secret-namespace: csi-rbd
      csi.storage.k8s.io/fstype: ext4
      imageFeatures: layering
      pool: rbd
    - clusterID: cluster2
      csi.storage.k8s.io/controller-expand-secret-name: cluster2
      csi.storage.k8s.io/controller-expand-secret-namespace: csi-rbd
      csi.storage.k8s.io/fstype: ext4
      imageFeatures: layering
      pool: rbd
provisioner: rbd.csi.ceph.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

Could it be possible to provision PVs from `cluster1` or `cluster2` depending on the zone or region in which the pod is scheduled?

Thank you very much for your help!
