### ISSUE TITLE
CephFS Helm Chart Fails to Template config.json in ConfigMap

### ISSUE THREAD

**Issue by cdav3435** [ceph/ceph-csi#4961]
# Describe the bug #

Deploying the CephFS CSI Plugin via Helm chart. `csiConfig` values in values.yaml are not rendered in csiplugin-configmap.

# Environment details #

- Image/version of Ceph CSI driver : 3.12.2
- Kubernetes cluster version : 1.31.1
- Ceph cluster version : 18.2.4

# Steps to reproduce #

values.yaml

```
---
csiConfig:
  - clusterID: "efadcb32-xxxx-xxxx-xxxx-5c9b1131c87a"
    monitors:
      - "10.xx.xx.91"
      - "10.xx.xx.92"
      - "10.xx.xx.93"
      - "10.xx.xx.94"
    cephFS:
      netNamespaceFilePath: "{{ .kubeletDir }}/plugins/{{ .driverName }}/net"
storageClass:
  create: true
  clusterID: "efadcb32-xxxx-xxxx-xxxx-5c9b1131c87a"
  fsName: cephfs
```

Render helm chart:

`helm template ceph-csi-cephfs ./ceph-csi-cephfs --dependency-update -n ceph-csi-cephfs --include-crds`

# Actual results

ceph-csi/charts/ceph-csi-cephfs/templates/csiplugin-configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: "ceph-csi-config"
  namespace: ceph-csi-cephfs
  labels:
    app: ceph-csi-cephfs
    chart: ceph-csi-cephfs-3.12.2
    component: provisioner
    release: ceph-csi-cephfs
    heritage: Helm
data:
  config.json: |-
    []
```

# Expected behavior #

ceph-csi/charts/ceph-csi-cephfs/templates/csiplugin-configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: "ceph-csi-config"
  namespace: ceph-csi-cephfs
  labels:
    app: ceph-csi-cephfs
    chart: ceph-csi-cephfs-3.12.2
    component: provisioner
    release: ceph-csi-cephfs
    heritage: Helm
data:
  config.json: |-
    [
      {
        "clusterID": "efadcb32-xxxx-xxxx-xxxx-5c9b1131c87a",
        "monitors": [
          "10.xx.xx.91",
          "10.xx.xx.92",
          "10.xx.xx.93",
          "10.xx.xx.94"
        ],
        "cephFS": {
          "netNamespaceFilePath": "/var/lib/kubelet/plugins/cephfs.csi.ceph.com/net"
        }
      }
    ]
```

# Logs #

I'm a little new to helm templating so I'm not sure what logs would be helpful for this.

# Additional context #

I've tried various values for csiConfig and haven't been able to get anything to render in config.json, but I can't see what I'm doing wrong. I looked through the helm template files and can't see anything that would cause this (.Values.externallyManagedConfigmap is set to false eg).
