### ISSUE TITLE
externally managed configmap

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#927]
The charts allow you to customize what configmap to use, but always try to create it. I'd like to use an externally to the chart managed configmap and noticed the conflict when setting the configmap name.

Can we add to values:
```
# Use an externally provided configmap
externallyManagedConfigmap: false
```

and wrap the configmap in:
```
{{- if not .Values.externallyManagedConfigmap }}

{{- end }}
```

**Comment by nixpanic** [comment]
This sounds reasonable to me. Care to send a PR for this?

**Comment by kfox1111** [comment]
I ran into one other issue while trying to plumb the helm chart to the configmap autogenerated by rook. The config file name is different in the configmap. I need a way to specify a mapping. I'll add that as well, and then submit a patch.

**Comment by kfox1111** [comment]
Looks like rook has this in its deployments/daemonsets:
```
        - name: ceph-csi-config
          configMap:
            name: rook-ceph-csi-config
            items:
              - key: csi-cluster-config-json
                path: config.json
```
So I need a way to specify which key to use from the configmap and add the mapping if specified. Should be easy enough to add.
